### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by wasamasa** [emacs-evil/evil#1]
- Is this in any way official?  If yes, where's the announcement?
- Will evil-related projects (like, goto-chg) get moved here?
- What do we use for communication?  An IRC channel on Freenode?

**Comment by TheBB** [comment]
Yes, it's official. There's no announcement at the moment, I'll ask Frank Fischer to make one soon.

I've only discussed the evil package specifically, and since that was the one looking for a maintainer I suggest we start there. It would be useful to have other common packages in under the same umbrella eventually, since many of them are a bit “adrift” (evil-indent-textobject comes to mind).

Whatever suits everyone. Spacemacs uses gitter. I believe there's already an `#evil` on freenode, right?

**Comment by TheBB** [comment]
Actually I was going to import the bitbucket issues, but the script I was using broke because you made this one. :-)

**Comment by wasamasa** [comment]
Ouch, sorry about that.  It strikes me as weird though because an API for programmatically creating issues should ideally not need to care about the ticket number on the target issue tracker.  In hindsight it might have been better to not invite me before importing issues...

`#evil` is abandoned, but has an active MLOCK policy, so I guess we'd need some perma-idlers and to chat with `#freenode` (who will undoubtedly suggest to use `#emacs-evil` instead) to get this resolved.

**Comment by TheBB** [comment]
Yeah no problem, it's running now. Probably my hack to make it work wasn't entirely correct but it's better than nothing.

**Comment by TheBB** [comment]
Hm, all the links are now offset. If you don't mind I'll delete this repository and recreate it with all the issues intact.

**Comment by wasamasa** [comment]
No problem for me.
