### ISSUE TITLE
Normal-state editing lag increases as Eshell coloured output grows

### ISSUE THREAD

**Issue by Ambrevar** [emacs-evil/evil#1006]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.26) of 2017-12-04
Operating System: Arch Linux
Evil version: 1.2.13
Evil installation type: MELPA
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No.

# Reproduction steps
- Start Emacs
- `M-x eshell`
- Insert lots of colored text.  On Linux, you can call `dmesg -L=always` a few times.
- Go to normal state and press `x` wherever you can delete a character.

# Expected behavior

Editing should happen instantly.

# Actual behavior

Normal-state editing induces a lag that seems related to the size of _coloured_ output in the Eshell buffer.
If you don't notice any lag, try filling your Eshell buffer with more coloured output.

**Comment by Ambrevar** [comment]
And here is the profiler CPU trace:

```
- command-execute                                                1694  90%
 - call-interactively                                            1694  90%
  - byte-code                                                    1675  89%
   - evil-operator-range                                         1147  61%
      evil-motion-range                                          1147  61%
   - ...
```

Looks like the bottleneck lies in `evil-motion-range`.

**Comment by wasamasa** [comment]
That's correct, I've found that the issue here is the call to `move-marker` in that function.  The Emacs manual notes that editing a buffer with many markers will be slow and unused markers should therefore be unset so that they can be garbage-collected. The reason why it only happens with colored output is because eshell handles this by calling out to `ansi-color-apply-to-region` which sets markers on every color boundary and never bothers cleaning up.  Therefore, this is unfortunately not a thing Evil could fix.

**Comment by Ambrevar** [comment]
Thank you for this report.

**Comment by Ambrevar** [comment]
Something I've noticed: if I run `clone-buffer`, the cloned buffer does not suffer any performance issue.
Is this because the cloned buffer does not contain any marker?
Looking at the code of `clone-buffer`, it seems that it does not copy markers.  (Maybe because it can't?)

Either way, it's good news: it means that the issue can be fixed.

**Comment by Ambrevar** [comment]
Reported upstream: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=29854.

**Comment by wasamasa** [comment]
It makes sense because markers are tied to a position in a buffer. To clone markers you'd need to iterate over them all, copy each you encounter and change the associated buffer (or alternatively, make a new one for that buffer with that position).  There doesn't appear to be any API for this, so no wonder it doesn't work.
