### ISSUE TITLE
evil-a-*-quote not working correctly when quote is escaped (org mode)

### ISSUE THREAD

**Issue by Shourai** [emacs-evil/evil#1032]
# Issue type

- Bug report

# Environment

Emacs version: 25.3.1
Operating System: macOS High Sierra
Evil version: 1.2.13
Evil installation type: Melpa
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs
- Go to scratch file
- Enter `org-mode`
- Paste the following lines:
```
"line 1"
"line 2\""
"line 3"
"line 4"
```
- enter `da"` on line 3

# Expected behavior

Entering `da"` on line three should give
```
"line 1"
"line 2\""

"line 4"
```
# Actual behavior

Instead it doesn't delete line 3 but somehow deletes the quote and joins the next line
```
"line 1"
"line 2\""
"line 3line 4"
```
# Further notes
It happens for backticks and single quotes aswell, there is no issue in other modes.

**Comment by dieggsy** [comment]
I can reproduce this. The behavior is present in text-mode, which org-mode is derived from.

**Comment by wasamasa** [comment]
These text objects require syntax tables being set up so that strings are recognized properly. This is the case in, say, `emacs-lisp-mode` but not `org-mode` (after all, strings are a thing in elisp code, in an Org file not so much). The rule of thumb is that if vanilla word/symbol movement doesn't work, Evil will break down as well. This is a deliberate choice because leveraging syntax tables allows us to avoid edge cases in how strings are handled and mode-specific exceptions, however it also exposes less than ideal modes.

As a workaround I could imagine something similar to the evil-matchit situation where you can enable a package that implements an alternative, albeit not as elegant implementation of `%`.

**Comment by Shourai** [comment]
@wasamasa, doesn't that mean that it shouldn't occur when you put those strings inside a source code block?
#+BEGIN_SRC emacs-lisp
"line 1"
"line 2\""
"line 3"
"line 4"
#+END_SRC
```
Shows the same behaviour.
Or does org-mode override that?
Because I would image that there might be cases where quotes are escaped inside source blocks.
```

**Comment by wasamasa** [comment]
Org source blocks don't change anything about syntax tables. While they use advanced trickery to copy syntax highlighting over, they don't do anything more than that, so it's to be expected the behavior is the same.

**Comment by Shourai** [comment]
Thank you for your explanation and follow up!
I'll look for a workaround :)
