### ISSUE TITLE
Square brackets mapping for editing python code

### ISSUE THREAD

**Issue by FelipeLema** [emacs-evil/evil#1043]
# Issue type

- Enhancement request

# Environment

Emacs version: GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.11) of 2018-04-16, unofficial emacs-snapshot build: http://emacs.ganneff.de/, git commit 6ec3ec7fbec2c04d5e9570b0470217cd97e5e7e6
Operating System: Devuan Ascii (Debian Stretch)
Evil version: Evil version 1.2.13
Evil installation type: MELPA
Graphical/Terminal: Both
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs
- Open the following python source file
- Place the cursor where marked
- Each destiny is marked with a comment

# Expected behavior

```python
class Mapping:                              # [[[[
    def __init__(self, iterable):
        pass

    def update(self, iterable):
        pass

    __update = update                       # []

class Reverse:                              # [[ or [m[m
    def __init__(self, data):               # [m
        self.data = data
        self.index = len(data)              # [M

    def __iter__(self):                     # <--- CURSOR
        return self                         # ]M

    def __next__(self):                     # ]m
        if self.index == 0:
            raise StopIteration
        self.index = self.index - 1
        return self.data[self.index]        # ][

class MappingSubclass(Mapping):             # ]] or ]m]m

    def update(self, keys, values):
        pass
```

# Actual behavior

```python
class Mapping:                              # (not landed)
    def __init__(self, iterable):
        pass

    def update(self, iterable):
        pass

    __update = update                       # (not landed)

class Reverse:                              # (not landed), (incorrectly landed with [[[[)
    def __init__(self, data):               # (incorrectly landed with [[ and [])
        self.data = data
        self.index = len(data)              # [ m is undefined 

    def __iter__(self):                     # <--- CURSOR
        return self                         # 
                                            # ][
    def __next__(self):                     # (incorrectly landed with ]])
        if self.index == 0:
            raise StopIteration
        self.index = self.index - 1
        return self.data[self.index]        # (not landed)

class MappingSubclass(Mapping):             # (not landed)

    def update(self, keys, values):
        pass
```

# Further notes

I learned about this [here](https://stackoverflow.com/a/28284564/3637404) while, indeed, looking for better ways to move around python code. I thought about working on this on a separate package, but then again, evil's supposed to mimic vim faithfully and this movement is present in vim (and neovim).

Seems pretty straightforward to do this, so I'll be working on a PR for this on my own.

On a side note, I feel kinda bad doing `(when (bound-and-true-p python-mode) …)` on several places, so maybe do overwriting setup on `python-mode-hook`?. Suggestions accepted.

**Comment by TheBB** [comment]
Evil mimics Vim to a point. Realistically Evil relies on Emacs internals for much of what it does, and sometimes they behave differently from Vim's internals. This is one of those cases.

`]]` and its cousins fall back on Emacs' `end-of-defun` and `beginning-of-defun` functions, which in Python defer to `python-nav-[beginning|end]-of-defun`, see `[beginning|end]-of-defun-function`. If you want to tweak this behaviour that's where you should be looking. You can change those in your `python-mode-hook`. Spreading guard clauses for various major modes around in Evil code won't do anyone much good.

`]m` and its cousins are undefined because Emacs doesn't have separate motions for sections and methods.

**Comment by FelipeLema** [comment]
All right, so I'm understanding correctly evil mimics evil only as close as vanilla/default Emacs provided tools will permit. This is news to me as Evil feels so complete. Is this actually documented?

Anyway, thanks everyone for taking the time to explain. I'll work on a separate package for this.

**Comment by wasamasa** [comment]
No, it strives for implementing the editing model of Vim (which is why things like Vimscript emulation are out of scope) and Emacs integration.  With that in mind, it makes no sense to ignore what Emacs modes provide and poorly reinvent the wheel.  Additionally to that, Evil providing integration code for every mode out there would be a bad engineering decision as it doesn't scale at all.  There are hundreds of major modes out there, do you seriously plan to put the definition for each into one package?  I mean, even the Stackoverflow answer you've linked tells you that the definition lives in a `python.vim`, their equivalent of a package.  It therefore makes most sense to leave the specifics to individual packages.
