### ISSUE TITLE
Emacs evil mode visual map `s` bindings

### ISSUE THREAD

**Issue by ChoppinBlockParty** [emacs-evil/evil#1082]
Seems like evil does not define bindings for s in visual mode. Do you know a good way of writing a function for emulating vim behavior of s?

**Comment by TheBB** [comment]
`s` is bound to `evil-substitute` in visual state, it seems to mirror vim's functionality to me. What binding did you have in mind? Note that vim-surround is not vim functionality and therefore not evil functionality either (but see https://github.com/emacs-evil/evil-surround).

**Comment by ChoppinBlockParty** [comment]
I checked I have no visual binding of `s` to `evil-substitute`, but I have it binded to in `evil-normal-state-map`. I finally figured out that I have an `s` binding with `evilem-define` (evil-easymotion). Why it is not displayed in `describe-binding` in `evil-visual-state-map`? Thank you for your help, sorry for wasting your time.

**Comment by TheBB** [comment]
No reason to apologize.

It's not the case that only one keymap is active at any given time. The normal state bindings are usable in visual state too, so long as there are no bindings in the visual state map that shadow them.

For example, there are no bindings in `evil-visual-state-map` for `hjkl` either, but they are still usable in that state because the normal state bindings are visible.
