### ISSUE TITLE
"turn-off-evil-mode" doesn't appear to work inside of a major-mode hook.

### ISSUE THREAD

**Issue by TyOverby** [emacs-evil/evil#1098]
# Issue type
- Bug report

# Environment

Emacs version: 21.6
Operating System: OSx
Evil version: Evil version evil-git-20e9619
Evil installation type: MELPA stable
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
1. Add the code 
```
(evil-mode 1)
(add-hook 'emacs-lisp-mode-hook 'turn-off-evil-mode)
```
To your emacs config file.
2. Run emacs and notice that evil mode is on
3. Open up an emacs lisp file
4. Notice that evil-mode is still on.

# Expected behavior
Evil mode should be disabled after being hooked

# Actual behavior
Turn-off-evil-mode doesn't work inside of the major mode hooks.

**Comment by TheBB** [comment]
I'm pretty sure the major mode hook runs before calling initializers for global minor modes, therefore all your hook does is turn off evil before it's turned back on again, because you have enabled evil-mode globally and therefore it's supposed to be on in that buffer.

The intended method to avoid using evil in certain buffers is to set the initial state to emacs state.

**Comment by TyOverby** [comment]
Is there another way to create a list of major modes for which evil-mode is blacklisted?

**Comment by TheBB** [comment]
Not at the moment, but PRs are welcome.
