### ISSUE TITLE
`goto-char` does not work in line visual state (`V`)

### ISSUE THREAD

**Issue by brabalan** [emacs-evil/evil#1136]
# Issue type
- Bug report

# Environment

Emacs version: 26.1
Operating System: Arch Linux, up to date
Evil version: evil-git-297b8f3
Evil installation type: elpa
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
- Start Emacs
- in the scratch buffer: `gg` `V` `M-: (goto-char (point-max))`

# Expected behavior
Visual line selection is extended to the end of the buffer

# Actual behavior
The point does not move, and the visual selection stays the same.

# Further notes
Initially reported as https://github.com/hlissner/doom-emacs/issues/975 but it is an evil-specific issue.

This bug might be related to #1108.

**Comment by dzop** [comment]
This looks like it has to do with how visual selection is updated in `pre-command-hook` and `post-command-hook` (see `evil-visual-pre-command` and `evil-visual-post-command`). `(goto-char (point-max))` is not evaluated as a command, the command loop is entered when you press `M-:` and the current command will be `eval-expression` when `(goto-char (point-max))` is evaluated.

I was able to get your example to work by doing

```emacs-lisp
(evil-set-command-property 'eval-expression :keep-visual t)
```

this effectively keeps visual state active after `eval-expression` completes. I don't think this would be a complete solution since you can run any arbitrary form with `eval-expression` even those where you would want visual state to be exited.

**Comment by brabalan** [comment]
Thank you for your investigation. My motivation for solving this is that in mu-compose mode, I cannot go to the bottom of the message using this function https://github.com/djcb/mu/blob/master/mu4e/mu4e-compose.el#L877. So with your suggestion I can set the property on this function and it works.

This solves my problem, but the underlying issue may remain, so I won't close this issue. Don't hesitate to close it if you disagree.

**Comment by dzop** [comment]
The recommended way to stay in visual state for commands that are external to Evil is to set the `:keep-visual` property on the command. So I think this issue can be closed since it doesn't make much sense to have `:keep-visual` on `eval-expression` for the reason I mentioned and it looks like what you really wanted to do was stay in visual state after running a non-Evil command.

**Comment by brabalan** [comment]
Sounds good, thanks again.
