### ISSUE TITLE
Why is git-commit-mode part of evil-emacs-state-modes?

### ISSUE THREAD

**Issue by telotortium** [emacs-evil/evil#1145]
Question:

It always frustrates me when I start a commit using Magit just to realize that the commit message buffer defaults to the Emacs state. Easy to fix with a `(delete 'git-commit-mode evil-emacs-state-modes)`. But why is it that way in the first place? Blame pointed me to https://github.com/emacs-evil/evil/commit/e1c1e20fe11685b33252d88106c7e6fdb5dadb5a, but the commit message doesn't say anything regarding that specifically.

Evil version: Evil version evil-git-41d891a
Evil installation type: MELPA

**Comment by dzop** [comment]
You would have to go back to d305ede1bbf6bf1989188c4e37d8abd3185f6698 since `git-commit-mode` is a replacement for the obsolete `magit-commit-mode`, but even in that commit there doesn't seem to be a reason for placing the mode in `evil-emacs-state-modes` other than to take into account new modes introduced by `magit`.

I think it would make sense to have `git-commit-mode` start off in insert state.

**Comment by TheBB** [comment]
I opened #1228 to fix this. Noting that evil-magit changes this mode to default (which is normal state, essentially), I feel it's fine following their lead.
