### ISSUE TITLE
Handle dash in ex command brokes `quelpa-upgrade`

### ISSUE THREAD

**Issue by kiennq** [emacs-evil/evil#1202]
# Issue type

- Bug report

# Environment
Emacs version: GNU Emacs 27.0.50 (build 1, i686-w64-mingw32) of 2019-09-19
Operating System: Windows 10
Evil version: Evil version 1.2.14
Evil installation type: MELPA
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
- Start Emacs
- Add [quelpa](https://framagit.org/steckerhalter/quelpa) using
``` elisp
  (let ((quelpa-pkg-dir (expand-file-name "quelpa/build/quelpa" user-emacs-directory)))
    (unless (file-exists-p quelpa-pkg-dir)
      (with-temp-buffer
        (url-insert-file-contents "https://framagit.org/steckerhalter/quelpa/raw/master/quelpa.el")
        (eval-buffer)
        (quelpa-self-upgrade))))
```
- Enable `evil`, type `:quelpa-upgrade`.

# Expected behavior
`quelpa-upgrade` is run.

# Actual behavior
`quelpa` is run.

This seems to be a regression of emacs-evil/evil#955. Since both `quelpa` and `quela-upgrade` command exists, with new parser logic typing `quelpa-update` will return to making `quelpa` running.

**Comment by kiennq** [comment]
Sample problem happens for `make-frame` too, `make` is invoked

**Comment by kiennq** [comment]
`evil-ex-argument-completion-at-point` is also affected. Cannot auto complete for function with `-` now, `make-` family is an example

**Comment by TheBB** [comment]
Thanks. Does #1202 fix your issues?

**Comment by kiennq** [comment]
Thanks for quick fix, changing evil grammar table also broken auto completion for now.
For example, `:make-<tab>` will not show any completion for `make-frame`.
I think you probably want to fix inside the `evil-ex-binding` itself?

**Comment by TheBB** [comment]
I pushed another commit. Can you try now?

Ultimately the problem is that marrying ex command grammar and Emacs commands isn't always possible. The ex mode should be for ex commands, and only incidentally allow to run Emacs commands.

There are two completion functions: one for commands and one for arguments. With the PR, the command completion will now run unconditionally (even outside of command context), but fall through to argument completion if no commands can be found.

I think this is a reasonable compromise, since ex commands with arguments almost never look like (prefixes of) Emacs commands, and I'm guessing 99% of completion usage is for the commands.

**Comment by kiennq** [comment]
Great, it works perfectly for me now. Thank you so much.

>Ultimately the problem is that marrying ex command grammar and Emacs commands isn't always possible. The ex mode should be for ex commands, and only incidentally allow to run Emacs commands. For the latter there is M-x and friends.

For me, I love the ability of `evil` to be able to marry Emacs and Vim command so seamlessly. Just `:` away and you can really access all command in `Emacs`, incredible.
