### ISSUE TITLE
Bind :e to alternative find-file implementations ('counsel-find-file)

### ISSUE THREAD

**Issue by hyiltiz** [emacs-evil/evil#1273]
# Issue type: 

- Question

# Environment

Emacs version: `GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.13, cairo version 1.16.0) of 2020-02-08, unofficial emacs-snapshot build: http://emacs.secretsauce.net`
Operating System: Debian
Evil version: "Evil version evil-git-59c95e7da" 
Evil installation type: MELPA
Graphical/Terminal: X
Tested in a `make emacs` session: Yes

# Expected behavior
How can I bind `:e[dit]` command to alternative implementations of `find-file`? I am using Emacs with `ivy`, and would like to use `counsel-find-file` or even `ido-find-file` when I do `:e`. However, I am getting an interface that looks like:
```
5 (): 
```
I looked at how `evil-edit` is implemented (`evil-ex-commands` says that is what `:edit` does). It seems it is hard-coded to use `find-file`. Is it possible to either overload that function, or to re-bind `:e` `:edit` etc. to something else?

**Comment by mohkale** [comment]
```
(bind-key [remap evil-edit] 'counsel-find-file counsel-mode-map)
```

**Comment by hyiltiz** [comment]
No, that would require me to `:e <RET>` to activate the mode.

**Comment by mohkale** [comment]
That's how ex commands work.

Could you clarify what you're trying to do here? 

Do you want to open the ex-command enter some text and then tab complete using `counsel-find-file`.

Ala `:e foo/ba<tab>` and then `counsel-find-file` pops up and lets you choose a completion candidate?

Are you trying to make it so that when you enter `:e ` `counsel-find-file` is automatically invoked? I don't recommend doing that, but you could probably bind something else to the space key and then check if the current ex prefix is a full command and if so invoke that. Still, not at all recommended.

Frankly I'd say just use `counsel-find-file` If you find it better for your workflow than the ex-commands.

**Comment by mohkale** [comment]
Have you tried doing something like this:

```elisp
(evil-define-command evil-edit2 (file &optional bang)
  "Open FILE.
If no FILE is specified, reload the current buffer from disk."
  :repeat nil
  (interactive "<f><!>")
  (if file
      (counsel-find-file file)
    (revert-buffer bang (or bang (not (buffer-modified-p))) t)))

(advice-add #'evil-edit :override #'evil-edit2)
```

this is identical to `(bind-key [remap evil-edit] 'counsel-find-file counsel-mode-map)` except it also takes whatever you pass through the ex command as the initial file path used by `counsel`. Personally I find it as if your you want to find the same file multiple times, once through evil and then through ivy. But whatever works I guess :smile:.

**Comment by hyiltiz** [comment]
This is what I was expecting: 
> Ala `:e foo/ba<tab>` and then `counsel-find-file` pops up and lets you choose a completion candidate? That's what it should do automatically if `counsel-mode` or `ivy-mode` is active.
