### ISSUE TITLE
Option to use non-incremental search?

### ISSUE THREAD

**Issue by singpolyma** [emacs-evil/evil#1304]
# Issue type

- Enhancement request

# Environment

Emacs version: GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.5) of 2019-09-22, modified by Debian
Operating System: Debian 10
Evil version: evil-git-d46eacd83
Evil installation type: spacemacs
Graphical/Terminal: Graphical

# Reproduction steps
- Start Emacs
- Press / and start typing

# Expected behavior

Should let me enter a search pattern, then hit enter to search (as in vim) -- search result should not be highlighted.

# Actual behavior

Search begins to jump around as soon as I begin to type, and draws highlighting everywhere.

# Further notes

I am currently working around this partially with:

```lisp
(defun singpolyma/search-forward-wrap (pattern)
	"re-search-forward but wraps at end"
	(let ((start (point)))
		(when (null (re-search-forward pattern nil t))
			(goto-char (point-min))
			(when (null (re-search-forward pattern nil t))
				(goto-char start)
				(re-search-forward pattern)
				)
			)
		)
	)

(defun singpolyma/evil-search (pattern)
	"Nonincremental search for evil mode"
	(interactive "s/")
	(setq regexp-search-ring (cons pattern regexp-search-ring))
	(evil-push-search-history pattern t)
	(singpolyma/search-forward-wrap pattern)
	(goto-char (match-beginning 0))
	)

(defun singpolyma/evil-search-next ()
	"Non highlighting search next for evil mode"
	(interactive)
	(forward-char)
	(singpolyma/search-forward-wrap (car-safe regexp-search-ring))
	;;(re-search-forward (car-safe regexp-search-ring))
	(goto-char (match-beginning 0))
	)
```

However, this is obviously only a partial workaround, it would be nice to have an official option, and also this has a bug I'm not sure how to fix (namely that `.` now repeats searches, which is very bad and annoying).

**Comment by mohkale** [comment]
what's your current value of `evil-search-module`? by default it's set to `isearch`. try setting to `evil-search` and see if your issue still persists.

**Comment by singpolyma** [comment]
@mohkale Either way I get this.  Setting to `evil-search` does seem to change the colour of the highlight?  But it still searches as I type instead of waiting until I hit RET

**Comment by mohkale** [comment]
I don't really see the evil behaviour here as a bug. It takes you to the first match of your search so you know what your searching, if you cancel the search you're taken right back to where you began.

If the highlighting is bothering you `(setq evil-ex-search-interactive nil)` seems to disable it for me. There's also `(setq evil-ex-interactive-search-highlight nil)` which disables the highlight on all but the first match.

I can't seem to find an option to stop evil moving the point as you search, I think it might be because under the hood it's using some parts of isearch which does this. Maybe someone else can help.

**Comment by singpolyma** [comment]
I never said it's a bug, but it's definitely a missing feature, especially when trying to replicate the (much nicer, IMO) behaviour of vim in this case.

**Comment by singpolyma** [comment]
If I could just use my functions (above) without having them change the behaviour of `.` that would be pretty great, even

**Comment by mohkale** [comment]
try this `(evil-put-command-property #'singpolyma/evil-search :repeat nil)`.

I'd also recommend using `evil-define-motion` instead of `defun` just so you don't have to set evil properties outside of function definition. See the definition of `evil-search-forward` if you have trouble with that. Good luck :smile:.

**Comment by singpolyma** [comment]
@mohkale Thanks! That fixes my main issue for now. Maybe I'll get it smoothed out a bit and figure out how to integrate enough to send a PR...
