### ISSUE TITLE
C-x C-; in evil-visual-line affects one too many lines

### ISSUE THREAD

**Issue by Atemu** [emacs-evil/evil#1346]
# Issue type

- Bug report

# Environment

Emacs version: 26.3 (https://github.com/NixOS/nixpkgs/commit/b50ef9afa11b384c72f7123ca4760ebc6d199fe8)
Operating System: NixOS (https://github.com/Atemu/nixos-config/commit/e024b6ffc1ccaa7b2bb315ce94e4b10fa5b38f05)
Evil version: evil-git-015303a70
Evil installation type: MELPA
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

(I was able to reproduce it using

```shell
nix-shell -E '{ pkgs ? import <nixpkgs> {} }:
with pkgs; mkShell {
  buildInputs = [ (emacsWithPackages [ emacsPackages.evil ]) ];
}' --run 'HOME=/var/empty emacs'
```

though which should be effectively the same. (evil 1.14))

# Reproduction steps
- Start Emacs
- Have n + 2 lines of text in a writable buffer
- Select the first n lines in evil-visual-line
- `C-x C-;`

# Expected behavior
It should comment/uncomment n lines

# Actual behavior
It comments/uncomments n + 1 lines

# Further notes

**Comment by Atemu** [comment]
I see.

If you try to reproduce this with regular emacs selection rather than visual mode, you'll notice that you have to select the newline character in order to delete the whole line rather than just the line content. Selecting the newline character in non-evil mode would result in your cursor jumping to the next line and `comment-line` then obviously also applies to that line.  
I assume evil-mode's visual mode simply makes it look like the cursor is still on the previous line here?

I think it'd be a good idea for evil-mode to override `C-x C-;` in visual mode to account for this fact.

**Comment by axelf4** [comment]
> I assume evil-mode's visual mode simply makes it look like the cursor is still on the previous line here?

Kind of. An overlay makes the region appear to cover whole lines, and pre-/post-command-hook:s set point and mark to be at BOL:s.

> If you try to reproduce this with regular emacs selection rather than visual mode, you'll notice that you have to select the newline character in order to delete the whole line rather than just the line content. Selecting the newline character in non-evil mode would result in your cursor jumping to the next line and comment-line then obviously also applies to that line. [...]

That is the thing: Visual-line selection has to be the way it is for `M-x delete-region RET` to do the right thing. If you do not want that then you should use a characterwise Visual selection instead.

> I think it'd be a good idea for evil-mode to override C-x C-; in visual mode to account for this fact.

After giving it some thought I disagree. `comment-line` exists solely because there is no such thing as Visual-line mode in vanilla Emacs; with Evil there are zero reasons to use it over `comment-or-uncomment-region` (`M-;` is even easier to type). Overriding it would just be an ugly hack.

There are easy fixes you can put in your init file which cannot be added to Evil proper:

* Remap `comment-line` to `comment-or-uncomment-region`.
* Add something like the following advice:

  ```elisp
  (define-advice comment-line (:before (_n))
    (let (end)
      (and (eq evil-this-type 'line)
           (save-excursion
             (<= (region-beginning) (progn (goto-char (region-end))
                                           (setq end (line-end-position 0)))))
           (if (< (mark) (point)) (goto-char end) (set-marker (mark-marker) end)))))
  ```
