### ISSUE TITLE
undo-redo require Emacs 28 message in Emacs <28

### ISSUE THREAD

**Issue by duianto** [emacs-evil/evil#1368]
- Enhancement request

It would be helpful to add a message that `undo-redo` requires Emacs 28, when it's used with Emacs <28.

source;
function definition is void: undo-redo https://github.com/syl20bnr/spacemacs/issues/14029

**Comment by wasamasa** [comment]
Why would you enable undo-redo when you don't have it? What's the sense behind that? Don't do that.

There's only so much handholding Evil can give you, the only reason there is any for undo-tree is because you need to have the `undo-tree-mode` enabled before `undo-tree-undo` and `undo-tree-redo` can be used (whereas you don't need such a thing for the `undo-redo` and `undo-only` commands).

**Comment by saffronsnail** [comment]
So does Evil mode not support Emacs 27 any more? There doesn't seem to be an option to have a default redo action unless you're upgraded to 28 or you have to have an extra package installed. My preferred distro is a little esoteric so I expect it to be behind sometimes, but even Arch is still on Emacs 27 (https://archlinux.org/packages/extra/x86_64/emacs/).

**Comment by TheBB** [comment]
Evil supports Emacs 27 just fine. You always needed an extra package for
undo. The only difference is that now you have a choice between two
packages, instead of being required to use undo-tree, and you have to make
that choice explicitly.
