### ISSUE TITLE
`gv` does not work in visual mode the same way as in Vim

### ISSUE THREAD

**Issue by justinhj** [emacs-evil/evil#1394]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 27.1 (build 1, x86_64-apple-darwin19.6.0, NS appkit-1894.60 Version 10.15.7 (Build 19H2)) of 2020-12-04
Operating System: macOS Catalina 10.15.7
Evil version: 1.14.0
Evil installation type: MELPA
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs
The issue comes when replicating this vim golf exercise where the winning key presses are `GyPgvr*ZZ`
http://www.vimgolf.com/challenges/5e4dfcccaa2db400090b66c3

Here I will make a minimal example of the problem

Start with an input file as follows

```
1
2
3
```

Using visual block mode and make a copy of the column so you get 

<C-v>GyP

```
11
22
33
```
Now us `gvr*` which in Vim will replace only the first column with *. In evil mode it instead selects both columns and replaces them with *.

```
**
**
**
```

# Expected behaviour

The final state of the file should be:

```
*1
*2
*3
```

# Actual behaviour
At the `gv` step it should select the original selection which is a single column at the start of the line. Instead, it selects two columns. Then when you replace the match with r it replaces two columns instead of one as desired.

The difference in behaviour between Evil and Vim is that the original selection is different (one column in Vim vs two columns in Evil/Emacs)

# Further notes

**Comment by tomdl89** [comment]
I'm happy to fix this, but I want to be sure this isn't a bug in vim. The vim docs for `gv` say:
>After using "p" or "P" in Visual mode the text that was put will be selected.

But it appears this is the case even if in normal mode (the mode you are in fact in when you press `P` in your `GyP` sequence), when pasting a block. This seems inconsistent with pasting of "text with other yank handlers" (to use emacs terminology). Vim is chock-full of exceptions to rules (many of them documented) so I don't oppose implementing this. I just can't see why anyone would want it to work this way. Admittedly, the way it works in Evil doesn't make sense either, so a change has to be made. If you (or anyone else) can explain why you'd want gv to select what you just pasted, rather than the last thing you had selected (i.e. the _right_ column in your example), that would be great. As it stands, the vim golf solution looks like it's exploiting a bug to emulate [this](https://vim.fandom.com/wiki/Selecting_your_pasted_text).

**Comment by justinhj** [comment]
It's hard for me to be objective since when comparing the behaviours in Emacs with evil and in vim I find the vim outcome less surprising, but then that's because I know it works that way. It certainly seems more useful than the current emacs behaviour. 
But as you point out, that last line in the documentation seems to suggest quite different behaviour.
I'm quite new to vim so I'd defer to the opinions of yourself and others on this, but my 2 cents would be that it's least surprising to do the same as vim despite the contradictions.

**Comment by PRESFIL** [comment]
You can increase the number of *columns* to *4* and reproduce this example from the 2nd column. You can see what `Vim does as described - restores the coordinates of the previous selection. And for some reason evil *doubles them in width*. You can also try an odd number of *5 columns* and start in the middle. If you select an arbitrary area without `G`, it will also double them.

**Comment by PRESFIL** [comment]
OK. :ok_hand:
