### ISSUE TITLE
Paredit not working as intended

### ISSUE THREAD

**Issue by eko234** [emacs-evil/evil#1458]
# Bug report
# Environment

Emacs version: GNU Emacs 27.2 (build 1, x86_64-w64-mingw32) if 2021-03-26
Operating System:  Windows 10
Evil version:  1.14.0
Evil installation type:  Melpa
Graphical/Terminal: Windows Terminal
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs
- Open any kind of buffer/file with some kind of s-expresion that holds other s-expresions inside which span multiple lines
- Try to use the command paredit-forward to navigate from the first inner sexp/atom to the tail of the outer sexp

# Expected behavior
- This should let you cross the lines between each internal sexp

# Actual behavior
- It gets stuck at the first line

# Further notes
- I've tried configuring the variables evil-cross-lines and evil-move-cursor-back and it doesn't work as expected.

**Comment by tomdl89** [comment]
Paredit is a totally separate package from evil. It's not even a dependency. Can you explain what relevance this bug report has to evil?

**Comment by eko234** [comment]
You are right, sorry, I can't find help about this issue, before i close this issue, could you please give me a hint on how to understand why and how would evil mode block navigation (moving the cursor) commands from other modes/functions?

**Comment by tomdl89** [comment]
It looks like `paredit-forward` needs to have moved _beyond_ a form in order to work when invoked again. Evil mode, by default, prevents moving beyond the end of a line (as vim does), so you'll need to do `(setq evil-move-beyond-eol t)` (or customize it, etc.) to let `paredit-forward` work at the end of a line. In case you're not aware, you may want to check out [lispyville](https://github.com/noctuid/lispyville) or [evil-cleverparens](https://github.com/luxbock/evil-cleverparens) as they are specifically designed to integrate lisp-editing with evil.

**Comment by eko234** [comment]
thanks :)
