### ISSUE TITLE
Cannot quit REPLACE state with a custom keybind

### ISSUE THREAD

**Issue by grolongo** [emacs-evil/evil#1472]
# Issue type

- Bug report

# Environment

Emacs version: 27.2
Operating System: Windows 10 and macOS (didn't test on Linux)
Evil version: 1.14.0
Evil installation type: Melpa
Graphical/Terminal: both Graphical and Terminal
Tested in a `make emacs` session: No

# Reproduction steps
- Start Emacs
- Use this config:
```elisp
(use-package evil
  :ensure t
  :bind (:map evil-insert-state-map
              ("C-g" . 'evil-force-normal-state))
  :config (evil-mode 1))
```
- Get in your `*scratch*` buffer, type some characters and go into `REPLACE` state (hit `R` from the `NORMAL` state).
  Now hit `C-g` to leave `REPLACE` state --> nothing happens.

# Expected behavior
I'm using `C-g` to quit `INSERT` state as I find it naturally easier and faster to type than reaching for the ESC key.
This works perfectly fine when I'm in `INSERT`, `VISUAL` or `VISUAL BLOCK` states and want to go back to the `NORMAL` state.
Unfortunately `C-g` doesn't work when I'm in `REPLACE` state.

# Actual behavior
When I'm in `REPLACE` state and hit `C-g` it doesn't quit back to `NORMAL` state, nothing happens.

**Comment by tomdl89** [comment]
If you want `C-g` to do `evil-force-normal-state` then you'll have to bind it in the `evil-replace-state-map` too. Replace state is completely separate from insert state, and does not use its keymap. It may seem that visual state and visual block state are respecting your `:bind`, but actually `C-g` returns you to normal state by default anyway (I'm not sure why - the inconsistency is probably not intentional, but not really a problem).

**Comment by grolongo** [comment]
@tomdl89 thank you a lot for your explanations. That fixed my problem.
