### ISSUE TITLE
Let minor mode keymap take precedence always in evil-motion-state

### ISSUE THREAD

**Issue by Inc0n** [emacs-evil/evil#1510]
# Issue type
- Enhancement request / Question

# Environment

Emacs version: 28.0.50
Operating System: 5.13.7-arch1-1
Evil version: 1.14.0
Evil installation type: MELPA
Graphical/Terminal: graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs

An example
- Open a directory with `find-file`, a dired mode buffer would appear. 
- Change the state of the buffer to `motion`
- Press `j`, the cursor will move to next line.
- Change state of buffer to `emacs`
- Press `j`, emacs will execute `dired-goto-file` instead now

# Expected behavior
I would like `dired-goto-file` to be the command to be executed, while in motion state. This would mean to let the current minor mode keymap to take precedence over the `motion` state. 

# Actual behavior
The `motion` state key binds are executed instead.

# Further notes
I am aware of this issue #511.  Where the solution is
> (evil-make-override-map git-timemachine-mode-map 'normal)
> (add-hook 'git-timemachine-mode-hook #'evil-normalize-keymaps)

However, what I wish is for motion state to let minor-mode key binds take precedence over the motion state key binds themselves.

**Comment by dylan-sessler** [comment]
@Inc0n I think this will work for your use-case.

From the [emacs manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/Remapping-Commands.html)

> A special kind of key binding can be used to remap one command to another, without having to refer to the key sequence(s) bound to the original command. To use this feature, make a key binding for a key sequence that starts with the dummy event remap, followed by the command name you want to remap; for the binding, specify the new definition (usually a command name, but possibly any other valid definition for a key binding).

> For example, suppose My mode provides a special command my-kill-line, which should be invoked instead of kill-line. To establish this, its mode keymap should contain the following remapping:

> `(define-key my-mode-map [remap kill-line] 'my-kill-line)`
Then, whenever my-mode-map is active, if the user types C-k (the default global key sequence for kill-line) Emacs will instead run my-kill-line.

And in your case, I think this should do the trick:
`(define-key dired-mode-map [remap evil-previous-line] 'dired-goto-file)`

Which will make it so that when you are in dired-mode, any time you run the command evil-previous-line it will instead run dired-goto-file.
