### ISSUE TITLE
Matches for `evil-search` don't stay highlighted until you cycle through the first couple of entries

### ISSUE THREAD

**Issue by sethen** [emacs-evil/evil#1521]
- Question

# Environment

Emacs version: 27
Operating System: Ubuntu 20.04
Evil version: evil-20210902.2016
Evil installation type: Melpa
Graphical/Terminal: GUI
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
Search doesn't work like it does in Vim

- Start Emacs
- `M-x` and `set-variable`
- Set `evil-search-module` to `evil-search`
- Type some words into the buffer like `next`
- Type `/n` and press enter

# Expected behavior

Results that begin with `n` should be highlighted and I should be able to see all of the matches highlighted at all times

# Actual behavior

Nothing is highlighted until I cycle through the first couple of results with `n`

# Further notes

**Comment by tomdl89** [comment]
The correct way to set the search module to evil-search is:
`(evil-select-search-module 'evil-search-module 'evil-search)`
Just setting the `evil-search-module` var is not enough, because it doesn't change the keybindings. When I first discovered this, I thought it was dumb, and I still do, but it's in enough people's configs that I don't think it's worth changing. You'll notice the strange highlighting bug goes away once you set your search module correctly.

**Comment by sethen** [comment]
That did it, thank you!
