### ISSUE TITLE
Change default value of evil-start-of-line to t

### ISSUE THREAD

**Issue by 0x28** [emacs-evil/evil#1535]
# Issue type
- Bug report

# Environment

Emacs version: 28.0.50
Operating System: Debian bookworm/sid
Evil version: 1.14.0
Evil installation type: MELPA
Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
- Start Emacs using `make emacs`
- Open nonempty buffer
- Move point to a column != 0
- invoke `evil-goto-first-line` `gg`

# Expected behavior
- Point should be in the first line and in column 0

# Actual behavior
- Point is in the first line but the column position is remembered 

# Further notes
The problem seems to be the default value of `evil-start-of-line`. The current default value is `nil` but the default value in vim is `on`. So it should probably be set to `t` by default. See also: [vimdoc for startofline](http://vimdoc.sourceforge.net/htmldoc/options.html#'startofline')

**Comment by tomdl89** [comment]
@0x28 thanks for the issue. I should assure you I gave this some thought before choosing `nil` rather than `t`. Although I can't deny evil aims to emulate vim, and makes no mention of neovim, I do tend to think us emacsers have more in common with the latter's users - who seem happy with this different default. I agree with neovim's relevant [commit](https://github.com/neovim/neovim/commit/3aa95ef27eb8817bc2ceddb6caf2b209e00a5e8d) which says:
> Having the cursor change column can be surprising.

But just because I agree with it, doesn't mean everyone will. I'll leave this issue open, and if it gathers substantial agreement, I'll make the change.

Out of interest, do you object to having to set this in your init.el to get the functionality you want, or are you concerned we'll surprise the vim purist newcomers?

**Comment by 0x28** [comment]
Setting it in my init.el is no problem for me, I was more concerned about surprising vim users, as you say. But I also didn't know about the neovim default. Nobody seemed to object to the issue in the neovim repository https://github.com/neovim/neovim/issues/11719. If the neovim users are ok with this default then I think it's also a good default for evil.
