### ISSUE TITLE
Backwards range behavior deviates from Vim

### ISSUE THREAD

**Issue by mcp292** [emacs-evil/evil#1628]
Issuing `:.,-10y` in Vim triggers a backwards range prompt as described in `:h E493`.

In evil, the prompt is not triggered and the behavior seems to be undefined.

**Comment by tomdl89** [comment]
I've had a quick stab at implementing a warning, but it's not easy. Seems that evil-parser is called repeatedly, which re-triggers any code to catch reversed ranges. Having looked at the code, it seems to always reverse the range, which I like because it's acting in a dwim way rather than vim's default of asking. However, if there seems to be undefined behaviour you have spotted, please give examples, because that is much more important. Thanks @mcp292 🙂

**Comment by mcp292** [comment]
That being said, and my agreeing with the dwim behavior, there seems to
be two remaining deviations from Vim in this context.

1: In Vim, with the file:
```txt
1
2
3
4
5
6
7
8
9
10
```

and your cursor on the zero of the ten, issue `:-5,.y`. The cursor
remains on the zero, and a subsequent put in Vim outputs:
```txt
5
6
7
8
9
10
```

In evil, a subsequent put outputs the same thing, but the cursor goes to
the top of the selection, putting it on the one. I only observe this
behavior in a fresh buffer, right after pasting "the file" of this post
into it. Subsequent calls behave like Vim.

2: In evil, backwards ranges do not equal forward range. `:-5,.y` with
the cursor on the zero of the ten yanks:
```txt
5
6
7
8
9
10
```

`.,-5y` yanks:
```txt
6
7
8
9
```

**Comment by tomdl89** [comment]
That's really helpful, thanks @mcp292  . Also, as you may have seen, I did end up finding a way to do the warning. Should have something pushed over the weekend.

**Comment by mcp292** [comment]
Glad you find it so. Nice work finding a solution!

**Comment by mcp292** [comment]
Found another possibly related one.
```txt
1
2
3
4
5
6
7
8
9
10
```

Put the cursor on the five, mark with `my`, go to the bottom with `G`, then issue `:'y,.y`. In Vim,
the cursor stays at the bottom.

**Comment by tomdl89** [comment]
@mcp292 all above issues should now be resolved in master. Please let me know if you observe otherwise.
