### ISSUE TITLE
Using evil macros to search for text crashes emacs

### ISSUE THREAD

**Issue by cptjimkirk** [emacs-evil/evil#1782]
In left buffer, I have a list of strings. I use those list of strings to search the right buffer.

Defining a macro, I record the following
```
yank next string
switch buffers
search via "/ C-r 0" to paste the text to search
text not found
emacs crashes
```
this happens 100% of the time when the string from the left buffer is not found in the right

**Comment by axelf4** [comment]
Please update the issue with more information (see the issue template!) As is, it is unactionable since I am unable to reproduce on GNU Emacs 28.2 and you did not specify what version you were running. Also, Emacs crashing hints at this being an Emacs bug instead of a bug in Evil-mode. Thus you may find more success reducing the problem and posting on the Emacs issue tracker instead.
