### ISSUE TITLE
Universal argument with custom operator

### ISSUE THREAD

**Issue by Mango0x45** [emacs-evil/evil#1817]
- Question

I would like to have a custom operator to sort lines, so I added the following to my `init.el`:

```elisp
(evil-define-operator mm--evil-sort-lines (beg end)
  "Wrapper around ‘sort-lines’ to allow for use as an ‘evil-mode’ operator."
  (sort-lines nil beg end))
```

This works fine for the most part, but I would also like to have a way to sort lines in reverse order.  Is it possible for me to make use of the universal argument (or something similar) in my operator?  Would be cool if I could do something like:

```elisp
(evil-define-operator mm--evil-sort-lines (beg end reverse)
  (interactive "P")
  (sort-lines reverse beg end))
```

**Comment by axelf4** [comment]
You should not use the universal argument in operators as it is [passed to the motion](https://github.com/emacs-evil/evil/blob/b291039b0c6ffc3b2f3c9f02b8ad2f0041127b12/evil-macros.el#L603-L606). Using a custom `interactive` spec is totally possible though, it just [defaults to `<r>`](https://github.com/emacs-evil/evil/blob/b291039b0c6ffc3b2f3c9f02b8ad2f0041127b12/evil-macros.el#L479). Look at examples in `evil-commands`. The simplest solution to your problem is to just define a second operator that sorts in reverse, or you could create an operator that enters Visual mode and opens the Ex prompt prefilled with ``:`<,`>sort``.

**Comment by Mango0x45** [comment]
> The simplest solution to your problem is to just define a second operator that sorts in reverse

Id rather not as I have lots of custom operators that do all sorts of things, and each one of those can have multiple ways of using them. So making more operators leaves me with the problem of running out of keys on my keyboard lol.

As for a custom `interactive` spec, where can I find documentation on that? I don’t see anything on the readthedocs page

**Comment by axelf4** [comment]
> As for a custom `interactive` spec, where can I find documentation on that?

I do not know about documentation, but the definitions of the different interactive codes are shown quite concisely if you lookup help for the variable `evil-interactive-alist`. These apply when defining commands with `evil-define-command` (or `evil-define-operator`/-`motion`/etc. whose expansions use `evil-define-command`) instead of the standard interactive codes. Note that e.g. the interactive code `<r>` maps to multiple function arguments.
