### ISSUE TITLE
Some unexpected behavior about point in visual selection

### ISSUE THREAD

**Issue by zbelial** [emacs-evil/evil#1822]
# Issue type
- Question

# Environment

Emacs version: 29.1
Operating System: Manjaro 22.1.3
Evil version: evil-git-162a94c
Evil installation type: manual
Graphical/Terminal: X
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
- Start Emacs with `emacs -Q` and the testing init.el (posted below)
- Open a file, eg. a file with these lines(without ")
"The first line
The second line"
- move cursor to (point-min)
- press `v`, then `e`, and the `e` again
- M-: (point) 
It will print 10 in *Message*
- press C-g to disable visual selection
- M-: (point)
This time, it will print 9 in *Message*

# Expected behavior
**Both the first `(point)` and the second one all print 10.**   

But I'm not sure whether the current behaviour is expected or not.  If it's, how can I make it behave as what I expected? 

# Actual behavior
As described above

# Further notes
testing init.el
```elisp
(add-to-list 'load-path "/path/to/goto-chg")
(add-to-list 'load-path "/path/to/evil")

(require 'goto-chg)
(require 'evil)
```

Thanks!

**Comment by axelf4** [comment]
The current behavior is intended I am afraid: In Visual state pre-/post-command-hook:s set the point and mark to match the visual selection during command execution (including `M-: ... RET`). This is necessary since characterwise-visual selection is inclusive-inclusive while the point&mark region used by non-Evil commands is inclusive-exclusive.

What is your use case?
