### ISSUE TITLE
How to make o/O use 4 spaces or a tab, it does 2 spaces.

### ISSUE THREAD

**Issue by leimath** [emacs-evil/evil#1937]
# Issue type

- Question

# Environment

Emacs version: `GNU Emacs 29.4 (build 3, x86_64-pc-linux-gnu, X toolkit, cairo version 1.18.0, Xaw3d scroll \
bars) of 2024-10-07
`
Operating System:  WSL2 + Ubuntu-24.04
Evil version:  `Evil version 1.15.0`
Evil installation type:  Elpaca
Graphical/Terminal:  terminal-emulator (wsltty)
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): 

# Reproduction steps
- Start Emacs

Open a C++ file.
Go to a line.
Press o.

# Expected behavior

I want it so that it either inserts a tab (size: 4) in the next line or 4 spaces.
# Actual behavior

Inserts 2 spaces. 

# Further notes

Noob tries to do stuff with tabs. Why is this so difficult.

```lisp
; START TABS CONFIG
;; Create a variable for our preferred tab width
(setq custom-tab-width 4)

;; Two callable functions for enabling/disabling tabs in Emacs
(defun disable-tabs () (setq indent-tabs-mode nil))
(defun enable-tabs  ()
  (local-set-key (kbd "TAB") 'tab-to-tab-stop)
  (setq indent-tabs-mode t)
  (setq tab-width custom-tab-width))

;; Hooks to Enable Tabs
(add-hook 'prog-mode-hook 'enable-tabs)
;; Hooks to Disable Tabs
(add-hook 'lisp-mode-hook 'disable-tabs)
(add-hook 'emacs-lisp-mode-hook 'disable-tabs)
(add-hook 'c++-ts-mode-hook 'enable-tabs)
(add-hook 'c-ts-mode-hook 'enable-tabs)

;; Language-Specific Tweaks
(setq-default python-indent-offset custom-tab-width) ;; Python
(setq-default js-indent-level custom-tab-width)      ;; Javascript

;; Making electric-indent behave sanely
(setq-default electric-indent-inhibit t)

;; Make the backspace properly erase the tab instead of
;; removing 1 space at a time.
(setq backward-delete-char-untabify-method 'hungry)

;; (OPTIONAL) Shift width for evil-mode users
;; For the vim-like motions of ">>" and "<<".
(setq-default evil-shift-width custom-tab-width)

(setq-default c-basic-offset custom-tab-width)
(setq-default standard-indent custom-tab-width)
;; WARNING: This will change your life
;; (OPTIONAL) Visualize tabs as a pipe character - "|"
;; This will also show trailing characters as they are useful to spot.
(setq whitespace-style '(face tabs tab-mark trailing))
(custom-set-faces
 '(whitespace-tab ((t (:foreground "#636363")))))
(setq whitespace-display-mappings
  '((tab-mark 9 [124 9] [92 9]))) ; 124 is the ascii ID for '\|'
(global-whitespace-mode) ; Enable whitespace mode everywhere
; END TABS CONFIG

```

I am using evil-collection and evil. I have no clue what to do. Read manuals but cannot wrap my head around which option to set/unset.

**Comment by tomdl89** [comment]
Setting `c-basic-offset` to `4` should be all you need afaik. That is, assuming you want `o`/`O` to follow the major-mode's indentation rules. If you want it to _always_ indent with 4 spaces, you will need to bind those keys to your own function, as that's not what `evil-open-below` was ever meant to do. Also on that assumption, this isn't an evil issue, as I can replicate this behaviour without evil (just pressing return at the end of lines). lmk if I'm missing something, and it is in fact evil-specific.

**Comment by imiric** [comment]
Hi, I'm having a similar issue with Go, where pressing `o` places the cursor at the beginning of the line, instead of using the default indentation for the current major mode or following the indentation of the current line.

Here's what I mean:

https://github.com/user-attachments/assets/29112aa5-1ff5-49ea-8d2e-f4191e602d30

I think this is indeed an issue with evil-mode, since when I turn it off and press Enter the cursor is placed at `\t\t|`, which is the behavior in Insert mode when evil-mode is enabled. The double tab is also unexpected, but at least it follows the indentation of the current line instead of placing the cursor at column 0.

Here's the behavior with evil-mode disabled:

https://github.com/user-attachments/assets/61906523-c3d0-4d1c-8d20-8f70a6436a68

I've tried every combination of settings mentioned here, including:
```elisp
(define-key global-map (kbd "RET") 'newline-and-indent)
```

...and other `newline` variants, but nothing seems to fix this.

Some guidance here would be deeply appreciated, as I'm not sure what combination of settings or packages is at fault here. I just want Go to have one tab worth of indentation, and for `o`/`O` to follow this setting in every scenario.

**Comment by imiric** [comment]
I finally had time to come back to this today, and your hint about treesitter mode was what lead me to the right path. Thanks @leimath! :bow:

I wasn't aware that `go-ts-mode` is now the default in recent Emacs versions instead of `go-mode`. I'm running 29.4.

So I removed the custom key binding I mentioned above, and my global config now has:

```
(setq electric-indent-mode nil)
(setq-default indent-tabs-mode nil)
(setq-default tab-width 2)
(setq-default standard-indent 2)
(setq-default c-basic-offset 2)
(setq-default sh-basic-offset 2)
(setq-default js2-basic-offset 2)
```

And the Go config has:
```
(use-package go-mode
  :ensure t
  :hook ((go-mode . own/go-mode-hook)
         (go-ts-mode . own/go-mode-hook))
  :config
  (defun own/go-mode-hook ()
    (setq indent-tabs-mode t)
    (setq tab-width 2)
    (setq go-ts-mode-indent-offset 2)))
```

This _mostly_ works as expected for Go and shell modes. There are still some quirks, but it's much better than before.

Thanks again, and Happy Holidays! :christmas_tree:
