### ISSUE TITLE
Propose `evil-ex-search-*` commands to show current matched word index and total matched word count

### ISSUE THREAD

**Issue by eval-exec** [emacs-evil/evil#1945]
# Issue type

- Enhancement request

# Environment

Emacs version: 30.0.50
Operating System: Nixos
Evil version: 1.15.0
Evil installation type: elpaca
Graphical/Terminal: graphical under Xwayland
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
- Start Emacs
- put cursor on a word, then hit `*`, I want `*` can display all word count in mode-line or echo area like vim:
![image](https://github.com/user-attachments/assets/9a56e9c8-95db-4e92-bbd5-cac3d8411198)
Above picture is in `vim` hit `*` key, vim will display current matched word index and total word matched count in bottom, I want evil-ex-search can display it as well.

# Expected behavior
Display matched word count and current matched word index in mode-line.

**Comment by tomdl89** [comment]
@eval-exec are you aware of https://github.com/emacsorphanage/evil-anzu?

**Comment by eval-exec** [comment]
Wow, Thank you! I need evil-anzu!

**Comment by linwaytin** [comment]
Sorry for replying to this closed issue, but I think `anzu` is not the ultimate solution. 
First, `anzu` is not really being maintained anymore. 
Moreover, emacs built-in `isearch` can show the index/count if `isearch-lazy-count` is set.
Since the default `evil-search-module` is `isearch`, it would be good to have this feature included.

**Comment by linwaytin** [comment]
I didn't notice that message, my bad. However, given both `vim` and `emacs` have this feature, and `evil`'s default search mechanism is using the built-in one, I still this it should be provided by `evil`, instead of another package.

**Comment by tomdl89** [comment]
I'm not sure what you mean by saying vim has this feature. Can you show me some docs / release notes to this effect?

**Comment by linwaytin** [comment]
I believe the screenshot posted by OP has shown this?

**Comment by tomdl89** [comment]
Ah, that was disabled in my vim by `shortmess` including `S`. Without that flag, I can indeed see it is part of vim. The only real difference I can immediately see is that anzu's count hangs around longer. So I'm guessing in the vim world, anzu isn't much used any more. In which, case I agree the ultimate solution would be for this functionality to be added to evil. Unfortunately I don't have the time/inclination to do that right now, but a PR would be welcome.

**Comment by linwaytin** [comment]
Ok I tried to dig into this problem. I use the `isearch` module.

1. The total number of matches is indeed stored in `isearch-lazy-count-total`, good.
However, the `isearch-lazy-count-current` has strange behavior for forward search (`/`). If I do not hit `n` to search forward, then it does save the current index. If I hit `n` to jump to the next match, this variable becomes 0. Now, if I hit `N` to jump backward, this variable saves the index again, but in the reverse order, i.e. counted from the end.

Any idea about this behavior? 

2. There is a variable called `evil-search-prompt`. The default is `nil`, but when I set it to some string, it does not show up in the search activated by `/` or `?`. Instead, it overwrites the prompt of `isearch-forward` and `isearch-backward`.

Is this behavior by design or kind of like a bug?
