### ISSUE TITLE
evil-digraph: How to add a digraph for '🙂' character

### ISSUE THREAD

**Issue by ju-sh** [emacs-evil/evil#1947]
# Issue type

- Question: How to add digraph for '🙂' character? I was trying to have ':)'

I think this is a 4-byte unicode character.
Is it possible to have digraphs for 4-byte unicode?

# Environment

Emacs version: 27.1
Operating System: Debian 11
Evil version: 1.15.0
Evil installation type: MELPA
Graphical/Terminal: X
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No

# Reproduction steps
Add this to init file:

```
((?: ?\)) . ?\xd83dde42)
```

# Expected behavior
Digraph should be loaded

# Actual behavior
Error message: `error: Hex character out of range: \xd83dde42...`

# Further notes
Not sure if I got the unicode hex for '🙂' wrong..

**Comment by tomdl89** [comment]
On my machine, that emoji looks to have a hex value of `#x1f642` so this should work:
```elisp
(push '((?: ?\)) . ?\x1f642) evil-digraphs-table-user)
```

but then so should just using the emoji literally in your init file:
```elisp
(push '((?: ?\)) . ?🙂) evil-digraphs-table-user)
```

**Comment by tomdl89** [comment]
_ChatGPT explanation if you are interested:_

In short, they were looking at the UTF-16 “surrogate pair” rather than the single Unicode code point.

## Single Code Point
+ The “slightly smiling face” emoji is U+1F642 in Unicode.
## UTF-16 Surrogate Pair
+ In UTF-16 encoding, characters outside the Basic Multilingual Plane (BMP) need two 16-bit code units.
+ For 🙂, the surrogate pair is 0xD83D 0xDE42.

So, when someone says “it’s U+d83dde42,” they are simply combining the two surrogate halves into one notation (D83D and DE42). It’s still the same emoji, but shown in UTF-16 rather than the single Unicode point in hex.

**Comment by ju-sh** [comment]
> but then so should just using the emoji literally in your init file:
> 
> `(push '((?: ?\)) . ?🙂) evil-digraphs-table-user)`

Thanks a lot for mentioning this!
Didn't know we could directly mention the symbol itself like this.
It works.

> In short, they were looking at the UTF-16 “surrogate pair” rather
> than the single Unicode code point.

👍
