### ISSUE TITLE
Evil Ctrl-o does not behave as in Vim

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#400]
Originally reported by: **Anonymous**

----------------------------------------

Evil Ctrl-o does not behave as in Vim. When I press Ctrl-o in Vim, then type :w, Vim executes the command and returns to the Insertion mode. On the other hand, if I do the same thing in Evil, emacs executes the command, but remains in the Normal mode.

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/400

**Comment by edkolev** [comment]
I can't reproduce this in `Evil version 1.2.12`, `Emacs 25.1.1`, maybe it has been fixed.

**Comment by wasamasa** [comment]
I'm not sure what this bug is about.  `C-o` jumps to another place, how is this related to insert mode?  Did the reporter possibly mean `M-o` (which in Vim is interpreted as `ESC o`)?  If yes, that's more of an interesting bug in Vim as it prevents it from recognizing key combinations starting with the meta key.

**Comment by edkolev** [comment]
Now I see the issue can be interpreted in different ways.

The way I understood it is:
1. enter in insert state
2. enter `C-o` in insert (from vim's `:help i_CTRL-O` `execute one command, return to Insert mode`)
3. enter `:w<CR>`
4. the user should now be back to insert state; however, the issue reporter reported that he's left in normal, instead of insert

**Comment by wasamasa** [comment]
Thanks, that explanation makes more sense.  That being said, I cannot reproduce what's described here, with `C-o` in insert state, I can execute `:w` just fine and end up back in insert state again.
