### ISSUE TITLE
stable request to melpa stable

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#458]
Originally reported by: **Joe M (Bitbucket: [joe9](https://bitbucket.org/joe9), GitHub: [joe9](https://github.com/joe9))**

----------------------------------------

Hello,

The current stable version of evil on stable melpa does not compile due to locked goto-chg. Can you please push the latest version of evil to stable melpa?

Thanks and Sorry for the bother,
Joe

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/458

**Comment by adc17** [comment]
Hey @TheBB, my understanding is that if you publish a tagged release to melpa, you are also publishing to melpa stable.

+1 for integrating goto-chg into evil, like the milkypostman comment suggests above. It would save melpa-stable users like me a lot of trouble. 

Sorry for bothering you, and hope this can be resolved. And thanks for all your super work on evil!

**Comment by ninrod** [comment]
Observe that the [comment](https://github.com/melpa/melpa/pull/2262#issuecomment-67528452) by @tarsius was actually mistaken and the issue was thus mistakenly closed. I think that `goto-chg` is still being fetched from the wiki. Maybe the best course of action is to ask to author, David Andersson, for maintainership of the goto-chg package. maybe it could be a brother of evil in the emacs-evil org.

**Comment by wasamasa** [comment]
Fixed as Evil can be installed from MELPA Stable.
