### ISSUE TITLE
Create [s and ]s motions for ispell

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#718]
Originally reported by: **Anonymous**

----------------------------------------

The thing I miss about vim is how easy it is to use spellcheck. With evil, to navigate to a misspelled word I have to press `b` until I reach the word. I really miss `[s` to travel to the last mispelled word, fixing it, and then returning to the last position of my cursor using `gi`.

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/718

**Comment by wasamasa** [comment]
`]s` can be implemented in terms of `flyspell-goto-next-error`, however this is not perfect for a number of reasons:

- Requires `M-x flyspell-buffer` to work correctly (which is OK as Vim also requires previous setup and errors out if you try using the aforementioned commands before)
- `z=` is using an ispell command, so that's sort of inconsistent
- No built-in equivalent for going the other direction
- Wrap-around behavior is different, in Vim it wraps around if you're going beyond the last/first word and the appropriate option is set, with Flyspell you get an irritating "No more miss-spelled word!" message (which is just wrong), only after that it wraps around

Writing my own commands based on some basic flyspell functions shouldn't pose much effort, so I'm giving that a try.
