### ISSUE TITLE
Test suite fails with Emacs 25

### ISSUE THREAD

**Issue by TheBB** [emacs-evil/evil#731]
Originally reported by: **Sean Whitton (Bitbucket: [spwhitton](https://bitbucket.org/spwhitton), GitHub: [spwhitton](https://github.com/spwhitton))**

----------------------------------------

* Emacs version: 25.1.1
* Evil version: commit `f2648b8`
* Operating system: Debian stretch

Several tests fails under Emacs 25:

```

10 unexpected results:
   FAILED  evil-test-insert-repeat-info
   FAILED  evil-test-normal-repeat-info-char-command
   FAILED  evil-test-normal-repeat-info-simple-command
   FAILED  evil-test-repeat
   FAILED  evil-test-repeat-append
   FAILED  evil-test-repeat-append-line
   FAILED  evil-test-repeat-insert
   FAILED  evil-test-repeat-insert-line
   FAILED  evil-test-repeat-open-above
   FAILED  evil-test-repeat-open-below
```

Full log attached.  Thanks.

----------------------------------------
- Bitbucket: https://bitbucket.org/lyro/evil/issue/731

**Comment by TheBB** [comment]
At least one of these failures (probably all) are dute to https://lists.gnu.org/archive/html/bug-gnu-emacs/2016-05/msg00635.html

We need to find a workaround, I guess.

**Comment by TheBB** [comment]
https://github.com/emacs-evil/evil/blob/master/evil-repeat.el#L330

Violating use of `this-command-keys` is here.

**Comment by noctuid** [comment]
From reading the linked discussion, it sounds like including the prefix argument in `(this-command-keys)` is not considered the correct behavior (which is sensible), and there won't be any changes to add this behavior back. The `prefix-arg` (when non-nil) should be recorded in the `pre` section of `evil-repeat-keystrokes` to fix this.

**Comment by TheBB** [comment]
Yeah, I'm just not sure to replicate that in a way that works with all the different ways users might have of specifying prefix arguments.

**Comment by noctuid** [comment]
I'm not sure I follow. It doesn't matter how it is set;`prefix-arg` holds the raw value.

**Comment by noctuid** [comment]
The issue is when it comes to repeating (not recording; the necessary information is available). Setting `prefix-arg` does not work with `execute-kbd-macro` ([relevant todo](https://github.com/emacs-evil/evil/blob/16eb854e18d1ec79b00a0a49c1f60aed710b303b/evil-repeat.el#L515)). It does work when setting `unread-command-events`, but it's very possible that using `unread-command-events` instead of `execute-kbd-macro` in `evil-execute-repeat-info` causes some other problems or breaks some other functionality.

The only way to have this work with `execute-kbd-macro` would be to mimic keys to set the prefix argument (and ensure those keys are bound to the right commands); I'm not sure if that's a good idea. Using a count wouldn't cover all cases. If something like `(this-command-prefix-keys)` existed, the old method could be used.

**Comment by TheBB** [comment]
Yes, that's what I mean.

**Comment by TheBB** [comment]
I had something like [this](https://github.com/TheBB/evil/commit/8c962e99d03c7f1c3ceb3a9b53b0543e9e35aa11) in mind.

Note the tests don't pass (yet) because they need to be rewritten if this is to be the solution, but repeats with counts do seem to work.

**Comment by noctuid** [comment]
That should be an okay workaround. It would need to handle the case where `prefix-arg` is a list though.

**Comment by djstauffer** [comment]
Just curious if there's been any progress on this issue.  I reverted to emacs 24.5 due to this bug (having '.' not work right is just unworkable for an old vim user like me :-D ).

I tried applying TheBB's patch, but I don't know enough about both emacs and evil mode's inter-workings to handle the case where prefix-arg is a list.  I did give it a try, but there was a lot of guessing, and ultimately no success.

**Comment by TheBB** [comment]
No, no progress unfortunately. My patch has secondary issues that are not so trivial to fix. I don't see any easy solutions. :-/

**Comment by djstauffer** [comment]
OK, thanks.  I wish I knew enough to help, but unfortunately I don't have time to allocate to learning everything I'd need to know in order to be of any use.

**Comment by djstauffer** [comment]
as I mentioned in issue #757, I'm going to try this out on 25.1 and see how it works for me.

**Comment by TheBB** [comment]
Oh yeah, we fixed this. I forgot. :-)
