### ISSUE TITLE
evil-window-decrease/increase-width should support Vi/Vim key bindings

### ISSUE THREAD

**Issue by naclander** [emacs-evil/evil#796]
In Vim, when wanting to resize a window, one can use ```C-w <``` or ```C-w >``` to resize the window left or right. This works great in evil-mode as well.

In Vim, one can also preface these commands by a number to do the action multiple times. So ```C-w 10 <``` or ```C-w 10 >``` would resize the window times 10 left or right. This currently does not work in evil.

I see that ```evil-widow-decrease-width``` and ```evil-window-increase-width``` support a ```COUNT``` argument already, so maybe what I'm trying to do is supported by another means, but it is not equivalent to the original vi/vim key bindings. 

Is there a plan to match the original vi/vim key bindings for this?

**Comment by wasamasa** [comment]
`10 C-w <` and `10 C-w >` work as expected, so I'd just use those instead.

Supporting `C-w 10 <` and `C-w 10 >` is a bit harder.  For that, the following should theoretically do:

```
(define-key evil-window-map "0" 'digit-argument)
(define-key evil-window-map "1" 'digit-argument)
(define-key evil-window-map "2" 'digit-argument)
(define-key evil-window-map "3" 'digit-argument)
(define-key evil-window-map "4" 'digit-argument)
(define-key evil-window-map "5" 'digit-argument)
(define-key evil-window-map "6" 'digit-argument)
(define-key evil-window-map "7" 'digit-argument)
(define-key evil-window-map "8" 'digit-argument)
(define-key evil-window-map "9" 'digit-argument)
```

Unfortunately it doesn't.  The same trick works for `evil-motion-state-map` because entering the prefix argument doesn't leave motion state.  With `evil-window-map` however this terminates the incomplete key sequence and exits that map.  While it is possible to hack around this (hello, helm!), I consider it too much work for little gain.
