### ISSUE TITLE
`c i "` does not work outside of function definitions in go mode

### ISSUE THREAD

**Issue by bomgar** [emacs-evil/evil#807]
I can reproduce the error with this go file 

```go
package x

const AUTH_HEADER_PREFIX = "X-Auth-"
```

Pressing `c i "` inside the string does not work. 

If i remove those to lines from the go-mode implementation the error disappears:
```elisp
(set (make-local-variable 'beginning-of-defun-function) #'go-beginning-of-defun)                                                                                                                                                                            
(set (make-local-variable 'end-of-defun-function) #'go-end-of-defun) 
```

I tested `c i "` inside a go function definition and i works without problems.

A comparison with the rust `beginning-of-defun` implementation shows that rust-mode moves to the beginnging of the line outside of a function definition while go-mode moves to the end of the line. In rust `c i "` works fine outside of function definitions.

**Comment by wasamasa** [comment]
Works for me with point *inside* a string and point at the start of the third line, but not with point somewhere else on the third line.  This appears to be an erroneous use of ppss because it doesn't use `save-excursion` unlike the later uses in `evil-forward-quote`.  Replacing `progn` with `save-excursion` resolves that third case for me.

Still, you might want to report a bug at https://github.com/dominikh/go-mode.el about https://github.com/dominikh/go-mode.el/blob/master/go-mode.el#L635-L636 which would explain this bizarre behavior.  Going to the end of line is the wrong direction for this kind of movement.
