### ISSUE TITLE
Screen flickers when saving a file with ":w" after updating to Emacs 25

### ISSUE THREAD

**Issue by rzetterberg** [emacs-evil/evil#820]
When I save a file using `:w` all text in the emacs window flickers, like it
removed all text and then rendered it from scratch. It mostly happens when
something is changed in the file.

When I instead use `C-x C-s` I don't have this problem.

This problem started happening after I updated to Emacs 25.

According to this reddit post there are 2 other people having the same
problem:
https://www.reddit.com/r/emacs/comments/5zcugj/saving_using_evils_w_sometimes_causing_the_screen/

I have been bisecting my config to the bare minimum where I can reproduce the
problem, comment out a line and the problem disappears.

My environment:

```
Linux 4.9.17 #1-NixOS x86_64 GNU/Linux

GNU Emacs 25.1.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.22.8)

Evil version 1.2.12
```

At the end of this issue is a script that sets up a clean emacs environment
with the problem reproduced and that cleans up after itself.

To see the problem for yourself, run the script, and when emacs is started
and have loaded the test file: move around, change some stuff and try saving
the file a couple of times with ":w" and you'll see all the text flickering.

Then change the script by removing the lines that turn of the toolbar and
scrollbar. Now you see that the problem is not encountered.

```bash
#!/usr/bin/env bash

tmp_dir=$(mktemp -d)

pushd "$tmp_dir"

touch ./test.org

cat <<EOF > ./test.org
,* INPROGRESS Post emacs bug report :emacs:
,* TODO Drink coffee :stuff:
,** TODO Clean coffee machine
,** DONE Clean coffee machine

- [ ] Check some checkboxes
- [ ] Don't check some checkboxes

,*** Some other stuff that I won't do :important:

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent interdum
lorem quis sapien malesuada pellentesque. Pellentesque at ultricies urna,
sed tristique magna. In facilisis volutpat arcu maximus lacinia.

Suspendisse aliquam dui tortor. Orci varius natoque penatibus et magnis
dis parturient montes, nascetur ridiculus mus.
EOF

cat <<EOF > ./init.el
(require 'package)
(setq package-enable-at-startup nil)

(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
(add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/"))
(package-initialize)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
    (package-install 'use-package))

(eval-when-compile
  (require 'use-package))

(when (fboundp 'tool-bar-mode)
 (tool-bar-mode -1))

(when (fboundp 'scroll-bar-mode)
 (scroll-bar-mode -1))

(use-package evil
  :ensure t
  :init
  :config
  (evil-mode 1))

(find-file "./test.org")
(show-all)
EOF

HOME="$tmp_dir" emacs --quick --load ./init.el

popd

rm -rf "$tmp_dir"
```

**Comment by wasamasa** [comment]
I don't see anything, except a mess of Wingdings:

![](http://i.imgur.com/vSSq4VZ.png)

Generally speaking, flicker is highly dependent on your graphics setup.  Emacs is known for [being less than optimal at redrawing](https://www.facebook.com/notes/daniel-colascione/buttery-smooth-emacs/10155313440066102), so depending on the Emacs version, the X version and what driver you're using, you can see it happen in the weirdest places.  I kept having flicker when typing an overly long line on IRC with Circe on Emacs 25 and after I've switched from the Intel to the modesetting driver, the problem was gone.  You might have luck with that solution as well and if not, try the bleeding edge build with the changes described in the above link.

**Comment by tjbrn** [comment]
Same problem here. This doesn't happened before.
