### ISSUE TITLE
Yanking a line removes wrong text's properties

### ISSUE THREAD

**Issue by d8660091** [emacs-evil/evil#855]
# Issue type

- Bug reports

# Environment
Emacs version: 25.2.1
Operating System: Arch
Evil version: 1.2.12
Evil installation type: MELPA
Graphical/Terminal: X

# Reproduction steps
in scratch buffer:
_(cursor)line1_

type yyp in normal mode -> 

_(cursor-old)line1
(cursor-new)line1(expect-position)_

# Expected behavior
Text properties of text between (cursor-new) and (expect-position) will be removed

# Actual behavior
Text properties of text between (cursor-old) and (cursor-new) is removed

# Further notes
remove-yank-excluded-properties may not be called properly.

When we yank a line, we use evil-paste-after which involves a calling to insert-for-yank-1. The insert-for-yank-1 removes the yanked text's text properties ([remove-yank-excluded-properties](https://github.com/emacs-mirror/emacs/blob/695d50fa0a11c6bd98f9f4a9b5a2905d33282316/lisp/subr.el#L3035)). However, in this context, the parameters for remove-yank-excluded-properties is wrong.

**Comment by wasamasa** [comment]
Well, if you consider them wrong, why did you report an issue with Evil?  That code is part of Emacs and I can only guess why it scrubs the text from `(point)` to the position of point after calling the yank handler:  In every vanilla Emacs scenario I can think of, the yanked text area is confined between these points, however for Evil it isn't as pasting doesn't necessarily result in text being inserted after point.  If you use `edebug` on `insert-for-yank-1`, you'll see that if you paste with Evil, the inserted text doesn't have any text properties and the area between point and its end is scrubbed, however with vanilla Emacs the inserted text still has text properties and gets scrubbed so that it doesn't have any afterwards.

I can't think up a good way to solve this problem, short of teaching Emacs that insertion of yanked text doesn't necessarily mean it will follow point.  A possible workaround would be to put point at the end of the line (for line copying actions), calling `insert-for-yank`, then restoring it.

**Comment by d8660091** [comment]
@wasamasa Thank you. The walk around sounds good.

**Comment by wasamasa** [comment]
It turns out that the workaround is wrong, I've replaced it with a better one and added a test. Thanks for reporting this!
