### ISSUE TITLE
Visual block, paste or insert from register issues

### ISSUE THREAD

**Issue by duianto** [emacs-evil/evil#906]
# Issue type
- Bug report

# Environment
Emacs version: GNU Emacs 25.2.2 (x86_64-w64-mingw32) of 2017-04-24
Operating System: Windows 10 Verison 1607 (OS Build 14393.1593)
Evil version: evil-git-a1101eb3
Evil installation type: MELPA (Installed/updated with Spacemacs, but loaded from the Spacemacs `.emacs.d` directory in Emacs like this:
1. `runemacs.exe -q`
2. `M-x package-initialize`
3. `M-: (require 'evil)`
4. `M-x evil-mode`)

Graphical/Terminal: Graphical
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): No
Vim version: 8.0.960

# Reproduction steps
- Start Emacs
- In the scratch or a new buffer, type:
```
abc
123
123
123
```
- Yank the `abc` word: `yiw`
- Block select the three 2's: `C-v`
- Paste: `p`

# Expected behavior
Evil should output the same thing as Vim:
```
abc
1abc3
1abc3
1abc3
```

# Actual behavior
```
abc
1abc3
13
13
```

# Further notes
There are also issues with pasting and inserting from a register with an active visual block, when `abc` has been copied as a line `yy`. It doesn't seem to work as expected in Vim either.

- Yank the `abc` line: `yy`
- block select the three 2's: `C-v`
- paste: `p`

Vim:
```
abc
13
13
13
abc
```
Evil:
```
abc
1
abc
3
13
13
```

Neither Vim nor Evil results in the expected output:
```
abc
1
abc
3
1
abc
3
1
abc
3
```
Inserting from a register:
- Copy the `abc` line: `yy`
- Block select the three 2's:  `C-v`
- Inserting from a register: `I C-r 0` (I = uppercase i)

Vim:
```
abc
1abc
23
123
123
```
Evil:
```
abc
1abc
2abc
3abc

123
123
```

Neither Vim nor Evil seems to work as expected. But I'm not sure if there should be a newline before `abc`, resulting in either:
```
abc
1abc
23
1abc
23
1abc
23
```
or
```
abc
1
abc
23
1
abc
23
1
abc
23
```

**Comment by wasamasa** [comment]
This should be two separate issues really, so I'm going to focus on the first as it's more clearly described than the second.  You might find `:help v_p` helpful for understanding the latter issue.

It appears that while Evil handles pastes in visual mode, it only considers it in a way that makes sense for character and line selection by replacing it with the pasted thing.  You'd have to enhance `evil-visual-paste` so that it checks for a block selection and does the right thing in that situation.

**Comment by ninrod** [comment]
>  You'd have to enhance evil-visual-paste so that it checks for a block selection and does the right thing in that situation.

@wasamasa, just hit this. About teaching `evil-visual-paste` to do the right thing in visual blocks, re you talking about [this](https://github.com/emacs-evil/evil/blob/c3317f8d1bd60405a2c3aad372da126651a74fbe/evil-commands.el#L1960-L1964)  snippet?

**Comment by robbert-vdh** [comment]
Any updates on this? I'm completely unfamiliar with evil's code base so I don't think I'd be able to easily fix this myself. I run into this issue quite often.

**Comment by nettoyoussef** [comment]
The only alternative I found on this was to insert from register, instead of pasting.
So, from OP:

```
abc
123
123
123
```

We go to `abc`, hit `yiw`, then `C-v + j + j + j` on the first 2, hit capital `I` to enter insert-mode, `Shift + Insert` and then enter normal mode (`ESC`):

```
abc
1abc23
1abc23
1abc23
```

Instead of `Shift-Insert`, `C-r {register}` also seems to work.

Not sure why this work and pasting does not, or what can really be done here, as my knowledge of lisp is very limited.

**Comment by tomdl89** [comment]
@nettoyoussef @robbert-vdh and of course @duianto (almost 5yrs later!) - this should now be fixed in master. With the exception of the last bit (`C-v I C-r 0` on linewise text, which now matches vim, and I think is too edge case for now), please let me know if you observe otherwise.

**Comment by nettoyoussef** [comment]
@tomdl89 I just have the time to update and test, and it works like a charm. 
Thanks a lot for your attention on this topic! :upside_down_face:
