### ISSUE TITLE
how to use `evil-range` to select text inside comment

### ISSUE THREAD

**Issue by redguardtoo** [emacs-evil/evil#909]
# Issue type
- Question

# Environment

Emacs version: 24.4.1
Operating System: debian 8.9
Evil version: 1.2.12
Evil installation type: manual
Graphical/Terminal: Terminal
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): Yes

# Reproduction steps
- Start Emacs
- In *scratch* buffer, input below code,
```lisp
;; third
;; a comment block
;; second line
```
- move cursor to the `t` of the line ";; third", press `C-v j $ j`

# Expected behavior
NA

# Actual behavior
I'm creating an inner text object to select text in this way.How to use `evil-range` to simulate this? Or any other API?  My last line of text object definition is like `(evil-range 4 42 'block :expand t)`.  It's obviously not right.

# Further notes

**Comment by wasamasa** [comment]
I'm not sure what exactly your problem is.  What do you intend to do with that range afterwards?  If it's to create a visual selection, use `evil-visual-select` or `evil-visual-make-selection`.  If it's to process the text, use `evil-apply-on-block` or `evil-apply-on-rectangle`.

**Comment by VanLaser** [comment]
I think it's about the so called "ragged selection" - in Vim, you can use `$` with visual block selection to select a block that goes to the end of *every* line in the selection, even if the lines are not equal. AFAIK this can't be done in emacs (well, maybe unless one activates artist-mode or something similar?). This ragged selection would be useful in order to select the contents of a multi-line block comment and create a text-object out of it.

**Comment by wasamasa** [comment]
That is done in block selection mode by setting `temporary-goal-column` and passing a special argument to `evil-apply-on-block` (as seen in `evil-apply-on-rectangle`).

**Comment by redguardtoo** [comment]
Thanks. I figure out  with your help:

select inner comment text object with irregular lines. https://github.com/redguardtoo/evil-nerd-commenter/issues/76
