### ISSUE TITLE
Dired 'h' help not accessible because 'h' is move cursor left

### ISSUE THREAD

**Issue by wolfv6** [emacs-evil/evil#921]
# Issue type
- Bug report

# Environment
Operating System: Linux Fedora 26
Evil version: evil-git-8e1af145
Evil installation type: MELPA stable from Spacemacs
Graphical/Terminal: Wayland
Terminal multiplexer: no
Tested in a [clean environment](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports): No

# Reproduction steps
- Start Emacs
- SPC SPC a d
- enter Dired
- enter '?' to display a list of Dired commands, h-elp
- enter 'h'

# Expected behavior
open Dired help

# Actual behavior
cursor moves left

# Further notes
'?' instead of 'h' is unresponsive.
Maybe a good way to fix this is to use '?' instead of 'h'.

**Comment by ninrod** [comment]
you have to try this procedure with a clean evil env. git clone the project and type `make emacs`. see [this](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports) entry on `contributing.md`

**Comment by VanLaser** [comment]
Also you have to expect that 1. using Evil necessarily changes bindings in *every* mode you enable evil in, 2. that you are supposed to customize Emacs+Evil+<each mode> to do what you expect it, and not push all expectations into evil integration, and 3. if you use Spacemacs, that distribution usually handles such evil<->modes integration, so you could/should first try to contribute with your integration there.

**Comment by ninrod** [comment]
about point `2.`, you could try to use [noctuid's general.el](https://github.com/noctuid/general.el). I'm using it to great success.

**Comment by wasamasa** [comment]
I can and will only speak about this bug without Spacemacs.  If you run a clean session as described above, open dired (with `C-x d`) and try the described keys, you'll notice that they'll do movement, like in an editing-related buffer, whereas keys like `c` and `?` do the dired-specific actions.  This is due to integration code in `evil-integration.el` which combines the emacsy keys with a hjkl override.  If you don't see this behavior, then that's Spacemacs' problem.  If you prefer completely vanilla behavior, switch to Emacs state by pressing `C-z` or make this a permanent customization by adding `(evil-set-initial-state 'dired-mode 'emacs)` to your init file.
