### ISSUE TITLE
Kakoune-style key bindings

### ISSUE THREAD

**Issue by nightscape** [emacs-evil/evil#924]
# Issue type
Enhancement request

I just stumbled upon [Kakoune](https://github.com/mawww/kakoune) and I'm quite amazed that it beats the VIM keybindings in terms of speed (required number of keypresses) and simplicity.
The main difference is that [Kakoune uses an **object** then **verb** grammar](http://kakoune.org/why-kakoune/why-kakoune.html) whereas VIM uses **verb** then **motion**.

Now I'm wondering if adding Kakoune-style keybindings to evil would be rather straight-forward or be completely opposite to the current model.
I'm not (yet) an Elisp programmer myself, so I could only tackle it in the first case...

**Comment by vyp** [comment]
I don't know anything about kakoune so I really have no any idea, but maybe https://github.com/mrkkrp/modalka could also be useful for someone who wishes to try and implement this.

**Comment by wasamasa** [comment]
It's rather tricky because Evil evolved towards very close Vim emulation rather than being a toolbox for creating your own modal editor.  Most of the magic regarding verbs and motions happens in `evil-operator-range`, macros are heavily used to make everything fit together.  You'd probably better off writing your own thing, like by using the above link.
