### ISSUE TITLE
Visual mode starts erratically and cursor jumps when xterm-mouse-mode is used in a text terminal

### ISSUE THREAD

**Issue by RafalLukawiecki** [emacs-evil/evil#960]
# Issue type

- Bug report

# Environment

Emacs version: GNU Emacs 25.3.1
Operating System: FreeBSD 11 and also macOS 13 HighSierra (might be a non-OS specific issue)
Evil version: Evil version 1.2.13
Evil installation type: MELPA
Graphical/Terminal: iTerm
Tested in a `make emacs` session (see [CONTRIBUTING.md](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md#bug-reports)): YES

# Reproduction steps
- Start Emacs in a text terminal (not GUI) that supports mouse events. I use iTerm. Ensure mouse events are not disabled in the terminal.
- `M-x <RET> xterm-mouse-mode` to enable mouse clicks being received.
- Type some text into a buffer.
- Click repeatedly within the text with a mouse.
 
# Expected behavior
Cursor should jump to the place mouse was clicked. Visual mode should not turn on. In other words, it should work the way it works in GUI, or in text, when evil mode is off, like after pressing `C-z` and continuing to click.

# Actual behavior
The result you will see is that *visual* mode will turn itself on and off whilst selecting parts of each clicked line starting at the the left edge of the line and ending at click point. However, cursor will jump to the beginning of the line. The resulting selection has no relation to what was clicked, it seems erratic. Further, *Messages* shows errors being logged while clicking: 
```
[ < is undefined
user-error: No previous search
```

![evil-emacs-xterm-mouse-mode-text-issue](https://user-images.githubusercontent.com/22912705/32408356-6071f73e-c18e-11e7-89cd-6ce9531ee866.png)

# Further notes
If evil-mode is then switched off using `C-z` the issue disappears. When it is switched back on, erratic behaviour resumes.

I have also reported it on the Emacs bug list, but it was suggested that I should report it here first. See my report over there: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=29143

Thank you for your help. Evil is my main editor nowadays and I appreciate your work. If I can help in any way, please let me know.

**Comment by wasamasa** [comment]
I suspect this is an issue specific to the terminal emulator and whether they support the events `xterm-mouse-mode` sends.  Termite for instance works as expected here whereas rxvt and xterm (oh the irony) exhibit the described behavior.  The only practical advice I have here is to not use Emacs in the terminal, it will save you much frustration.

**Comment by RafalLukawiecki** [comment]
Thank you for your comment, @wasamasa. I have little choice but to use the terminal when I work with a good few remote servers. I can use vim in those cases, of course, but I would prefer to use emacs and evil. Mouse makes things easier, sometimes, too.

Could you suggest any workarounds for this issue? Do you understand what is causing it? Can you suggest any other place where I can find out more how to resolve it, or have you found any other discussions about it? I have searched for a few hours before composing this bug report, but I could not find anything except for one unanswered SO post.

I am sorry that you have marked this as "wontfix"—no disrespect is meant, as I am _very grateful_ for your hard work. I really like evil-mode. Thank you.

**Comment by wasamasa** [comment]
I don't understand what happens here and as it involves actually understanding how terminal emulators and the respective Emacs code work, I will not dive any further into it. If http://invisible-island.net/xterm/ctlseqs/ctlseqs.html doesn't scare you off, maybe you're the one to solve this mystery. 

As for other workarounds, well, some people use TRAMP, some don't edit code on remote servers at all (and sync with scp/rsync/ftp/...), others use provisioning software to declaratively deploy changes to servers, etc. I don't want to get into a discussion about how everyone is supposed to do their work, but workarounds do exist plenty.

**Comment by RafalLukawiecki** [comment]
Vasilij, I am looking for a workaround to the mouse issue in emacs-evil, not a workaround to how to work with code and remote servers—but I appreciate the suggestion you have made, too. Perhaps there is a way to trap that error in code, or to stop visual mode from being triggered by mouse events?

I browsed the mouse-related section (not very long) of the (long) document that you have linked to. It seems that mouse clicks and positions are reported in a well-described way, and one which Emacs-without-evil interprets correctly. You seem to suggest that to fix this issue one would need to perform xterm and mouse interaction within evil itself. I suppose I do not understand if/how evil intercepts the xterm mouse events, or if it places Emacs into a mode that makes it misinterpret those events.

You know much, much more about evil-mode and Emacs than I do. Perhaps you could clarify if, in your opinion, this is:
- a bug in iTerm and xterm (I can report to them the incorrect xterm mouse behaviour)
- a bug in Emacs core (Eli Zaretskii from gnu.org would like to know if this is a core Emacs bug as per his comment https://debbugs.gnu.org/cgi/bugreport.cgi?bug=29143#14),
- a bug in evil-mode.

If it is the latter, is the reason not to want to fix it due to a lack of resources or is it just too difficult to fix? Thank you for your kind opinions, I appreciate your help.

**Comment by wasamasa** [comment]
It's hard to tell whose fault it is.  What I can tell currently is that debugging this would be a major headache and not worth it for me, compared to using a perfectly fine working alternative like GUI Emacs.  From what I can see there are the following parts to this puzzle:

- Terminal emulators implement the above set of rules inconsistently
- Terminal emulators are configurable to the extent of making some inconsistencies disappear
- Emacs works around these inconsistencies, but doesn't catch all of them
- Emacs emulates xterm-style mouse handling by sending escape sequences that will hopefully work for the terminal emulator, but doesn't attempt handling errors
- Emacs has mouse handling code that's a major pain to debug as it catches all kinds of mouse events, then translates them to the correct ones
- Evil contains an old copy of that mouse handling code with a few patches so that visual mode is integrated into it
- Evil itself hooks itself into Emacs' event handling, sometimes by using relatively unknown tricks for this (such as binding menu bar items to a key translation)

The cost to benefit ratio of this is bad enough that I marked this as Wontfix. If someone hands in a PR that helps with this situation, I'd probably accept it.

**Comment by RafalLukawiecki** [comment]
Thank you, Vasilij, for explaining your reasoning. I appreciate the time you have put into it, very much. Even though you prefer GUI in your current work, there still are, and there will be for a _long_ time, many text-based circumstances where a GUI/TRAMP/sshfs/rsync/git/svn/Puppet/Jenkins/etc workflow does not suit them. This is part of the reason I have used vim and emacs for such a long time, and I still do, rather than a "modern GUI" ones like Sublime or various IDEs.

I hope someone stumbles upon this thread and has a bright spark of a suggestion how to fix it. In the meantime I will have to do without evil for a while...

Thank you, again, for your time.

**Comment by Eli-Zaretskii** [comment]
I know nothing about Evil mode, so apologies in advance if the below makes no sense.

That said, looking at evil-maps.el, I see no bindings of any kind for mouse-1, for example (which AFAIU was what the OP tried and expected to behave as described above).  So I wonder whether some additional bindings in the same maps as those used under "Mouse" in evil-map.el could fix the problem.  In addition, would binding "[<" and "[M" to the respective xt-mouse.el functions help?

I have a feeling that I'm missing something, because if the solution was so easy, Vasilij wouldn't have tagged this "wontfix".  But if this is the case, would it be possible to point out what am I missing, and where is that "old copy of mouse handling code" mentioned above?  (I found `evil-esc` etc., but that just processes escape sequences, and I see no code processing mouse emulation sequences.)

TIA

**Comment by wasamasa** [comment]
@Eli-Zaretskii I implore you to scroll all the way to the top of this page, enter "mouse" in the search box and hit `RET`.  You'll immediately find said mouse handling code and wonder no more.

**Comment by Eli-Zaretskii** [comment]
Humor me.

**Comment by RafalLukawiecki** [comment]
The workaround of `(with-eval-after-load 'evil-maps (define-key evil-motion-state-map [down-mouse-1] nil))` solves my immediate need: I can again use evil-mode in text terminals with mouse support. If a better fix is possible, please update this issue when that happens, if you do not mind.

I appreciate your help, @wasamasa and @Eli-Zaretskii very much. I use evil-mode + Emacs several hours every day. I have high respect for your time as much as I am grateful for the entire developer community who have created them. Thank you.

**Comment by RafalLukawiecki** [comment]
By the way, as this issue has also been reported on StackOverflow by someone else, I have posted your workaround over there, too: https://stackoverflow.com/questions/46513910/emacs-evil-mode-binding-mouse-event/47122921#47122921

**Comment by fice-t** [comment]
@Eli-Zaretskii Evil replaces `mouse-drag-track` with `evil-mouse-drag-track`, which is based off of a 5-6 year old version of `mouse-drag-track`. It's in `evil-commands.el`.

I tried porting `evil-mouse-drag-track` to the most recent version of `mouse-drag-track`, and it seemed to fix this issue (I don't really use evil-mode, so the change might break other parts). I ran into 3 main issues:

1. The new code uses `lexical-binding`. Evil should probably use it anyway.
2. `evil-visual-activate-hook` runs during the `set-transient-map` stage, and it needs to be disabled while that's running, otherwise the visual state is toggled when single clicking in place.
3. Double clicking puts the cursor one character too far, for some reason. I believe it has to do with `mouse-set-region`, which since Emacs 25 is called after releasing `mouse-1`.
This can be fixed by advising `mouse-set-region` in Emacs 25+. Though perhaps there's a better solution.

**Comment by monnier** [comment]
@fice-t: I think ideally, rather than replace `mouse-drag-region` altogether, Evil should "just" use hooks within it to make it do what it needs.  Of course, it probably doesn't have the needed hooks right now, so please `M-x report-emacs-bug` to try and see what hooks could be added to `mouse-drag-region` so that Evil doesn't need to replace it.

**Comment by wasamasa** [comment]
That still leaves me with making things work for Emacs 24.3 to whatever version is the last one to not have these hooks.  That would at the very least be 25.3, but likelier 26.1, too. I suspect the best solution for these is something like https://github.com/raxod502/el-patch, really.

**Comment by monnier** [comment]
It's an orthogonal issue: whether you ask for new hooks or not, you'll have to try and make it work with the current Emacsen.  The difference is about maintenance of Evil in the future and about benefits for the whole community (since you can reasonably presume that some of those new hooks could prove useful for others as well).  Evil is already 6 years old, and given its breadth and popularity, it's likely to exist for a lot longer than that.  Ten years from now, support for Emacs-25 will be largely irrelevant.

**Comment by wasamasa** [comment]
I'm inclined to just dyke that piece of code out as it's more of a pain than a benefit.  If @monnier, @Eli-Zaretskii or whoever else is itching to make `mouse.el` less terrible, go ahead, but don't drag me into this.  I don't even understand why you keep pinging me about an issue marked as WONTFIX.

**Comment by monnier** [comment]
Until someone describes what Evil needs changed from mouse-drag-region (which is what I referred to as "please M-x report-emacs-bug ..."), I won't know what you mean by "make mouse.el less terrible".

**Comment by fice-t** [comment]
@RafalLukawiecki #964 should fix this.

@monnier I agree, ideally 3rd party packages shouldn't (have to) replace large chunks of mouse handling code. I see a few obvious places for hooks, but there are a couple of oddities (`#2/#3` in my previous comment) when using the newer mouse handling code with Evil. Someone that actually understands it (`#3` especially) should move forward with this, if there's such a person that cares to do so.

@wasamasa 
> I'm inclined to just dyke that piece of code out as it's more of a pain than a benefit.

It seems painful in its current state, but I see that as more of a reason to fix it rather than drop it. Isn't some evil-specific mouse handling code necessary to provide accurate emulation to vim's mouse handling? The code apparently hasn't been touched since 2014, so while annoyingly large it doesn't seem to need much attention.

**Comment by wasamasa** [comment]
@fice-t I can imagine a different way of going at this.  Considering that the main difference with the functionality disabled is that a mouse selection is always interpreted as a character region (as opposed to a line-wise one for a triple-click) and the boundaries can be off by one (such as when dragging from right to left and letting go), I can imagine a wrapper command that inspects the mouse state and applying the relevant Evil functions to work. It would be a lot less invasive than the current solution and possibly equivalent to how it used to be back then.
