### ISSUE TITLE
Deleting lines with <D> in visual selection not behaving the same as in Vim

### ISSUE THREAD

**Issue by tsoernes** [emacs-evil/evil#967]
- Bug report

# Environment
Spacemacs 0.200.10@25.3.1
Fedora 27
# Reproduction steps
```
one
two
three
four
```
Put the cursor on the t in two and start a selection with v, then move to the end of the line with $, now when D is pressed, both line two and three are deleted.

# Expected behavior
Just line two should be deleted

# Actual behavior
Deletes lines 2 and 3

**Comment by wasamasa** [comment]
Please don't rewrite the bug report template just because you happen to use Spacemacs.

**Comment by duianto** [comment]
#### Possible cause:
In the example above, the `region-end` is at the start of line `three`, and the last line of the 
`evil-delete-line` operator:
https://github.com/emacs-evil/evil/blob/5337d2b3d2f739b4b5b4a73bc0e66363be6b71f9/evil-commands.el#L1394

deletes from the `region-beginning` to the end of the line.

#### Possible solution:
If it doesn't cause other issues, then maybe `(line-end-position)` could be changed to `evil-visual-end`.
Because this command `(evil-delete (region-beginning) evil-visual-end)` only deletes the lines that are visually selected.

**Comment by duianto** [comment]
Nvm, that probably won't work, since it should delete the whole line, and `evil-visual-end` could be in the middle of a line.
