### ISSUE TITLE
Deleting lines with <D> in visual selection not behaving the same as in Vim

### ISSUE THREAD

**Issue by tsoernes** [emacs-evil/evil#968]
# Issue type
- Bug report

# Environment
Emacs version: Spacemacs 0.200.10@25.3.1
Operating System: Fedora 27
Evil version: evil-git-4bb4cb46
Evil installation type: MELPA
Graphical
Tested in a `make emacs` session: No

# Reproduction steps
- Start Emacs
```
one
two
three
four
```
Put the cursor on the t in two and start a selection with v, then move to the end of the line with $, now when D is pressed, both line two and three are deleted.
# Expected behavior

Just line 2 should be deleted
# Actual behavior
Deletes lines 2 and 3
# Further notes
There are no further notes.

**Comment by tsoernes** [comment]
Just to add; this behavior is different from vim (where only line 2 is deleted in the previous scenario).

**Comment by tsoernes** [comment]
Whats the status on this

**Comment by edkolev** [comment]
@tsoernes would you like to try to address this? You'll probably need to modify `evil-delete-line` https://github.com/emacs-evil/evil/blob/master/evil-commands.el#L1376 when `type` is `line` (around line 1401)

**Comment by tsoernes** [comment]
I've taken a look but can't come up with anything, sorry

**Comment by smile13241324** [comment]
@edkolev I have had a look into this and I am not sure whether this is really only an issue of the delete function. Whenever a range is selected which includs the \n sign of the line. Expand-range-line will expand to the next line though actually the end marker should not be touched in that case. 

A very simple solution may be to substract one from "end" in case of line expansion thus removing the \n from the selection before the expansion is done. However I am unsure whether this should be done in evil-delete-line or in expand-range-line. 

Can you advice?

**Comment by smile13241324** [comment]
Add a fix in `evil-delete-line` tested this locally and it seems to have no side effects.

**Comment by wasamasa** [comment]
The choice depends upon whether this is specific to deletion or not.

**Comment by smile13241324** [comment]
@wasamasa 

The problem should not be related to the specific behaviour of vim. Its rather a hack to fix an undesirable behaviour of `(line-beginning-position 2)` which only happens if `evil-expand-line` is called with `end` after the line's `\n`.

With this being said, the behaviour can only occur when we are in visual state and the entire line is marked otherwise `\n` would not be after `end` and line expansion would work as expected. In this mode we would need to call something that would use line expand to trigger the error.

I have played a bit around and found the following cases being affected when in visual state and the region contains the line's `\n`:
* D to delete the marked line, but does delete two lines
* Y to yank the marked line, but does yank two lines
* X to delete the marked line, but does delete only the marked area (I think this is a separate issue)
* C to delete the marked line and change into insert mode, but does delete two lines than changes into insert mode
* S to delete the marked line and change into insert mode, but does delete only the marked area (I think this is a separate issue)

My current code change does only fix the `D` case but leaves the others untouched. To have this solved entirely I think `evil-expand-line` would have to be adjusted to detect when it would malfunction and in this case operate on `end-1` to avoid the issue. I think the change would be necessary in evil-types.el line 131.

Should I attempt to make a fix in `evil-expand-line` or would you like to merge the fix for `D` and make the changes in `evil-expand-line` yourself later?

**Comment by tsoernes** [comment]
Also, the same problem exists for yank line <Y>

**Comment by wasamasa** [comment]
I'd prefer to have the change in one place if possible. If refactoring is needed for it to be this way, I'd have no issue with that.

I don't have `evil-expand-line` here, are you referring to the `(evil-define-type line ...)` definition?

**Comment by smile13241324** [comment]
Yes I mean the definition in `(evil-define-type line ...)`. I will try to fix the issue in `evil-types.el`.

**Comment by schickele** [comment]
I've just stumbled across this bug while deleting some visual-selected with capital 'D' in Evil. The region/selection ended with a newline. The line below the selection disappeared too, as mentioned here. From what I understand, smile13241324 came up with a fix in spring 2018, but the push request has been ignored. I'm unable to be of help myself, but wanted to draw the attention to it, just in case someone who is also bothered by this passes by. Here is a little demonstration:

![demo](https://github.com/emacs-evil/evil/assets/36489836/47d08d07-217c-4642-94a6-5a8c18b8a29b)

**Comment by tomdl89** [comment]
@schickele this should now be fixed in master. Please let me know if you observe otherwise.

**Comment by schickele** [comment]
Thank you very much, Tom! It works as expected now:

![demo1](https://github.com/emacs-evil/evil/assets/36489836/2aa12603-d836-4282-ad3e-4bbb86ed54fe)


If for some reason you are in Basel this summer, let me buy you a beer ,-)
