### ISSUE TITLE
what's the and operator in evil's regexps

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [emacs-evil/evil#977]
# Issue type

- Question

# Reproduction steps
- Start Emacs
- type `ABCD CDEF ABEF`
- type `/AB\&EF`

# Expected behavior

highlight `ABEF`

# Actual behavior

not match

# further notes
the `\&` is and operator in vim
it seems there is no relative operator in emacs

**Comment by wasamasa** [comment]
There isn't indeed. I strongly suggest to read the Emacs Lisp reference on regular expressions to know what's supported and what isn't.  While Evil is capable of emulating some of Vim's regex, reimplementing Vim's regex engine in Emacs Lisp is out of the question because it would be unbearably slow for questionable benefit.
